// Code generated by Fern. DO NOT EDIT.

package integrations

import (
	context "context"
	os "os"

	gosdk "github.com/islo-labs/go-sdk"
	core "github.com/islo-labs/go-sdk/core"
	internal "github.com/islo-labs/go-sdk/internal"
	option "github.com/islo-labs/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("ISLO_API_KEY")
	}
	if options.APIVersion == "" {
		options.APIVersion = "2026-09-15"
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Return the integration providers available to connect from Islo, including the supported authentication methods and connection scopes.
//
// Example:
//
//	client.Integrations.ListIntegrationProviders(
//	    context.TODO(),
//	)
func (c *Client) ListIntegrationProviders(
	ctx context.Context,
	opts ...option.RequestOption,
) (*gosdk.IntegrationProvidersResponse, error) {
	response, err := c.WithRawResponse.ListIntegrationProviders(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Integrations.ListIntegrationTriggers(
//	    context.TODO(),
//	)
func (c *Client) ListIntegrationTriggers(
	ctx context.Context,
	opts ...option.RequestOption,
) (*gosdk.TriggerCatalogListResponse, error) {
	response, err := c.WithRawResponse.ListIntegrationTriggers(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &gosdk.GetIntegrationTriggerRequest{
//	    Provider: "provider",
//	    TriggerName: "trigger_name",
//	}
//	client.Integrations.GetIntegrationTrigger(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetIntegrationTrigger(
	ctx context.Context,
	request *gosdk.GetIntegrationTriggerRequest,
	opts ...option.RequestOption,
) (*gosdk.TriggerCatalogItem, error) {
	response, err := c.WithRawResponse.GetIntegrationTrigger(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List the integrations the user/tenant has connected.
//
// Includes preset providers (from the PROVIDERS registry) and tenant-scoped
// custom outbound apps (filtered out of Descope's load_all_applications).
// Returns one entry per connected (provider, scope, auth_type) slot, so a
// provider with both a personal api_key and a personal oauth token will
// appear twice. Disconnected slots are not emitted; clients that need a
// list of available-but-not-connected providers should call
// “GET /integrations/providers“ instead.
//
// Example:
//
//	client.Integrations.ListIntegrations(
//	    context.TODO(),
//	)
func (c *Client) ListIntegrations(
	ctx context.Context,
	opts ...option.RequestOption,
) (*gosdk.IntegrationListResponse, error) {
	response, err := c.WithRawResponse.ListIntegrations(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List custom service definitions in the current tenant (catalog view).
//
// Returns every custom Descope app belonging to the tenant regardless of
// connection status, so the Add Integration picker can surface them for
// any tenant member to connect to. Connection state (per-user/per-workspace
// tokens) lives on “GET /integrations“; this endpoint is purely the
// service catalog.
//
// Example:
//
//	client.Integrations.ListCustomServices(
//	    context.TODO(),
//	)
func (c *Client) ListCustomServices(
	ctx context.Context,
	opts ...option.RequestOption,
) (*gosdk.CustomServicesResponse, error) {
	response, err := c.WithRawResponse.ListCustomServices(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a tenant-scoped custom Descope outbound app.
//
// Returns the “app_id“ so the frontend can immediately kick off the
// connect flow (OAuth) or surface the API key form. Presets do not pass
// through this endpoint -- their app ids come straight from
// “GET /integrations/providers“.
//
// Example:
//
//	request := &gosdk.CustomServiceCreateRequest{
//	    Custom: &gosdk.CustomIntegration{
//	        Name: "name",
//	        Slug: "slug",
//	    },
//	}
//	client.Integrations.CreateCustomService(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateCustomService(
	ctx context.Context,
	request *gosdk.CustomServiceCreateRequest,
	opts ...option.RequestOption,
) (*gosdk.CustomServiceCreateResponse, error) {
	response, err := c.WithRawResponse.CreateCustomService(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Disconnect a custom integration by its Descope app ID.
//
// Authorization is by deterministic-ID prefix: only apps whose ID matches
// “cust-{tenant-prefix}-“ are accepted, which scopes the operation to the
// caller's workspace without a DB lookup. “scope“ selects which side's
// tokens to revoke (per-user vs tenant-wide); “delete_app=true“ removes
// the Descope app entirely (affects every user in the workspace).
//
// Example:
//
//	request := &gosdk.DisconnectCustomIntegrationRequest{
//	    DescopeAppID: "descope_app_id",
//	}
//	client.Integrations.DisconnectCustomIntegration(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DisconnectCustomIntegration(
	ctx context.Context,
	request *gosdk.DisconnectCustomIntegrationRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.DisconnectCustomIntegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the detailed status of a specific integration.
//
// Returns both user-level and tenant-level connection status independently.
//
// Example:
//
//	request := &gosdk.GetIntegrationStatusRequest{
//	    Provider: "provider",
//	}
//	client.Integrations.GetIntegrationStatus(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetIntegrationStatus(
	ctx context.Context,
	request *gosdk.GetIntegrationStatusRequest,
	opts ...option.RequestOption,
) (*gosdk.IntegrationDetailResponse, error) {
	response, err := c.WithRawResponse.GetIntegrationStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Disconnect/revoke an integration.
//
// Args:
//
//	provider: Provider name
//	level: Which level to disconnect (USER or TENANT)
//	auth_type: Optional. Defaults to provider's primary type.
//
// Example:
//
//	request := &gosdk.DisconnectIntegrationRequest{
//	    Provider: "provider",
//	}
//	client.Integrations.DisconnectIntegration(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DisconnectIntegration(
	ctx context.Context,
	request *gosdk.DisconnectIntegrationRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.DisconnectIntegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Integrations.ListConnectedIntegrationTriggers(
//	    context.TODO(),
//	)
func (c *Client) ListConnectedIntegrationTriggers(
	ctx context.Context,
	opts ...option.RequestOption,
) (*gosdk.TriggerCatalogListResponse, error) {
	response, err := c.WithRawResponse.ListConnectedIntegrationTriggers(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
