// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
	time "time"
)

type CloudRoleCreate struct {
	Provider               CloudProvider  `json:"provider" url:"-"`
	Type                   *CloudRoleType `json:"type,omitempty" url:"-"`
	RoleArn                string         `json:"role_arn" url:"-"`
	SessionDurationSeconds *int           `json:"session_duration_seconds,omitempty" url:"-"`
}

type DeleteCloudRoleRequest struct {
	RoleID string `json:"-" url:"-"`
}

type GetCloudRoleRequest struct {
	RoleID string `json:"-" url:"-"`
}

type ListCloudRolesRequest struct {
	// Filter by role type
	Type *CloudRoleType `json:"-" url:"type,omitempty"`
}

type CloudProvider string

const (
	CloudProviderAws   CloudProvider = "aws"
	CloudProviderGcp   CloudProvider = "gcp"
	CloudProviderAzure CloudProvider = "azure"
)

func NewCloudProviderFromString(s string) (CloudProvider, error) {
	switch s {
	case "aws":
		return CloudProviderAws, nil
	case "gcp":
		return CloudProviderGcp, nil
	case "azure":
		return CloudProviderAzure, nil
	}
	var t CloudProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CloudProvider) Ptr() *CloudProvider {
	return &c
}

type CloudRoleResponse struct {
	ID                     string     `json:"id" url:"id"`
	Provider               string     `json:"provider" url:"provider"`
	Type                   string     `json:"type" url:"type"`
	RoleArn                string     `json:"role_arn" url:"role_arn"`
	SessionDurationSeconds int        `json:"session_duration_seconds" url:"session_duration_seconds"`
	IsEnabled              bool       `json:"is_enabled" url:"is_enabled"`
	IsloTrustRoleArn       string     `json:"islo_trust_role_arn" url:"islo_trust_role_arn"`
	CreatedAt              *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt              *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CloudRoleResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloudRoleResponse) GetProvider() string {
	if c == nil {
		return ""
	}
	return c.Provider
}

func (c *CloudRoleResponse) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CloudRoleResponse) GetRoleArn() string {
	if c == nil {
		return ""
	}
	return c.RoleArn
}

func (c *CloudRoleResponse) GetSessionDurationSeconds() int {
	if c == nil {
		return 0
	}
	return c.SessionDurationSeconds
}

func (c *CloudRoleResponse) GetIsEnabled() bool {
	if c == nil {
		return false
	}
	return c.IsEnabled
}

func (c *CloudRoleResponse) GetIsloTrustRoleArn() string {
	if c == nil {
		return ""
	}
	return c.IsloTrustRoleArn
}

func (c *CloudRoleResponse) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CloudRoleResponse) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CloudRoleResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CloudRoleResponse) UnmarshalJSON(data []byte) error {
	type embed CloudRoleResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CloudRoleResponse(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	c.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CloudRoleResponse) MarshalJSON() ([]byte, error) {
	type embed CloudRoleResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewOptionalDateTime(c.CreatedAt),
		UpdatedAt: internal.NewOptionalDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *CloudRoleResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CloudRoleType string

const (
	CloudRoleTypeGateway CloudRoleType = "gateway"
	CloudRoleTypeCompute CloudRoleType = "compute"
)

func NewCloudRoleTypeFromString(s string) (CloudRoleType, error) {
	switch s {
	case "gateway":
		return CloudRoleTypeGateway, nil
	case "compute":
		return CloudRoleTypeCompute, nil
	}
	var t CloudRoleType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CloudRoleType) Ptr() *CloudRoleType {
	return &c
}

type CloudRoleUpdate struct {
	RoleID                 string  `json:"-" url:"-"`
	RoleArn                *string `json:"role_arn,omitempty" url:"-"`
	SessionDurationSeconds *int    `json:"session_duration_seconds,omitempty" url:"-"`
	IsEnabled              *bool   `json:"is_enabled,omitempty" url:"-"`
}
