// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	cloudRoleCreateFieldProvider               = big.NewInt(1 << 0)
	cloudRoleCreateFieldType                   = big.NewInt(1 << 1)
	cloudRoleCreateFieldRoleArn                = big.NewInt(1 << 2)
	cloudRoleCreateFieldSessionDurationSeconds = big.NewInt(1 << 3)
)

type CloudRoleCreate struct {
	Provider               CloudProvider  `json:"provider" url:"-"`
	Type                   *CloudRoleType `json:"type,omitempty" url:"-"`
	RoleArn                string         `json:"role_arn" url:"-"`
	SessionDurationSeconds *int           `json:"session_duration_seconds,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CloudRoleCreate) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleCreate) SetProvider(provider CloudProvider) {
	c.Provider = provider
	c.require(cloudRoleCreateFieldProvider)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleCreate) SetType(type_ *CloudRoleType) {
	c.Type = type_
	c.require(cloudRoleCreateFieldType)
}

// SetRoleArn sets the RoleArn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleCreate) SetRoleArn(roleArn string) {
	c.RoleArn = roleArn
	c.require(cloudRoleCreateFieldRoleArn)
}

// SetSessionDurationSeconds sets the SessionDurationSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleCreate) SetSessionDurationSeconds(sessionDurationSeconds *int) {
	c.SessionDurationSeconds = sessionDurationSeconds
	c.require(cloudRoleCreateFieldSessionDurationSeconds)
}

func (c *CloudRoleCreate) UnmarshalJSON(data []byte) error {
	type unmarshaler CloudRoleCreate
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CloudRoleCreate(body)
	return nil
}

func (c *CloudRoleCreate) MarshalJSON() ([]byte, error) {
	type embed CloudRoleCreate
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteCloudRoleRequestFieldRoleID = big.NewInt(1 << 0)
)

type DeleteCloudRoleRequest struct {
	RoleID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteCloudRoleRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetRoleID sets the RoleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteCloudRoleRequest) SetRoleID(roleID string) {
	d.RoleID = roleID
	d.require(deleteCloudRoleRequestFieldRoleID)
}

var (
	getCloudRoleRequestFieldRoleID = big.NewInt(1 << 0)
)

type GetCloudRoleRequest struct {
	RoleID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCloudRoleRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetRoleID sets the RoleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCloudRoleRequest) SetRoleID(roleID string) {
	g.RoleID = roleID
	g.require(getCloudRoleRequestFieldRoleID)
}

var (
	listCloudRolesRequestFieldType = big.NewInt(1 << 0)
)

type ListCloudRolesRequest struct {
	// Filter by role type
	Type *CloudRoleType `json:"-" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListCloudRolesRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCloudRolesRequest) SetType(type_ *CloudRoleType) {
	l.Type = type_
	l.require(listCloudRolesRequestFieldType)
}

type CloudProvider string

const (
	CloudProviderAws   CloudProvider = "aws"
	CloudProviderGcp   CloudProvider = "gcp"
	CloudProviderAzure CloudProvider = "azure"
)

func NewCloudProviderFromString(s string) (CloudProvider, error) {
	switch s {
	case "aws":
		return CloudProviderAws, nil
	case "gcp":
		return CloudProviderGcp, nil
	case "azure":
		return CloudProviderAzure, nil
	}
	var t CloudProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CloudProvider) Ptr() *CloudProvider {
	return &c
}

var (
	cloudRoleResponseFieldID                     = big.NewInt(1 << 0)
	cloudRoleResponseFieldProvider               = big.NewInt(1 << 1)
	cloudRoleResponseFieldType                   = big.NewInt(1 << 2)
	cloudRoleResponseFieldRoleArn                = big.NewInt(1 << 3)
	cloudRoleResponseFieldSessionDurationSeconds = big.NewInt(1 << 4)
	cloudRoleResponseFieldIsEnabled              = big.NewInt(1 << 5)
	cloudRoleResponseFieldIsloTrustRoleArn       = big.NewInt(1 << 6)
	cloudRoleResponseFieldCreatedAt              = big.NewInt(1 << 7)
	cloudRoleResponseFieldUpdatedAt              = big.NewInt(1 << 8)
)

type CloudRoleResponse struct {
	ID                     string     `json:"id" url:"id"`
	Provider               string     `json:"provider" url:"provider"`
	Type                   string     `json:"type" url:"type"`
	RoleArn                string     `json:"role_arn" url:"role_arn"`
	SessionDurationSeconds int        `json:"session_duration_seconds" url:"session_duration_seconds"`
	IsEnabled              bool       `json:"is_enabled" url:"is_enabled"`
	IsloTrustRoleArn       string     `json:"islo_trust_role_arn" url:"islo_trust_role_arn"`
	CreatedAt              *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt              *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CloudRoleResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloudRoleResponse) GetProvider() string {
	if c == nil {
		return ""
	}
	return c.Provider
}

func (c *CloudRoleResponse) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CloudRoleResponse) GetRoleArn() string {
	if c == nil {
		return ""
	}
	return c.RoleArn
}

func (c *CloudRoleResponse) GetSessionDurationSeconds() int {
	if c == nil {
		return 0
	}
	return c.SessionDurationSeconds
}

func (c *CloudRoleResponse) GetIsEnabled() bool {
	if c == nil {
		return false
	}
	return c.IsEnabled
}

func (c *CloudRoleResponse) GetIsloTrustRoleArn() string {
	if c == nil {
		return ""
	}
	return c.IsloTrustRoleArn
}

func (c *CloudRoleResponse) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CloudRoleResponse) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *CloudRoleResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CloudRoleResponse) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetID(id string) {
	c.ID = id
	c.require(cloudRoleResponseFieldID)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetProvider(provider string) {
	c.Provider = provider
	c.require(cloudRoleResponseFieldProvider)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetType(type_ string) {
	c.Type = type_
	c.require(cloudRoleResponseFieldType)
}

// SetRoleArn sets the RoleArn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetRoleArn(roleArn string) {
	c.RoleArn = roleArn
	c.require(cloudRoleResponseFieldRoleArn)
}

// SetSessionDurationSeconds sets the SessionDurationSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetSessionDurationSeconds(sessionDurationSeconds int) {
	c.SessionDurationSeconds = sessionDurationSeconds
	c.require(cloudRoleResponseFieldSessionDurationSeconds)
}

// SetIsEnabled sets the IsEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetIsEnabled(isEnabled bool) {
	c.IsEnabled = isEnabled
	c.require(cloudRoleResponseFieldIsEnabled)
}

// SetIsloTrustRoleArn sets the IsloTrustRoleArn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetIsloTrustRoleArn(isloTrustRoleArn string) {
	c.IsloTrustRoleArn = isloTrustRoleArn
	c.require(cloudRoleResponseFieldIsloTrustRoleArn)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetCreatedAt(createdAt *time.Time) {
	c.CreatedAt = createdAt
	c.require(cloudRoleResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleResponse) SetUpdatedAt(updatedAt *time.Time) {
	c.UpdatedAt = updatedAt
	c.require(cloudRoleResponseFieldUpdatedAt)
}

func (c *CloudRoleResponse) UnmarshalJSON(data []byte) error {
	type embed CloudRoleResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CloudRoleResponse(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	c.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CloudRoleResponse) MarshalJSON() ([]byte, error) {
	type embed CloudRoleResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewOptionalDateTime(c.CreatedAt),
		UpdatedAt: internal.NewOptionalDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CloudRoleResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CloudRoleType string

const (
	CloudRoleTypeGateway CloudRoleType = "gateway"
	CloudRoleTypeCompute CloudRoleType = "compute"
)

func NewCloudRoleTypeFromString(s string) (CloudRoleType, error) {
	switch s {
	case "gateway":
		return CloudRoleTypeGateway, nil
	case "compute":
		return CloudRoleTypeCompute, nil
	}
	var t CloudRoleType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CloudRoleType) Ptr() *CloudRoleType {
	return &c
}

var (
	cloudRoleUpdateFieldRoleID                 = big.NewInt(1 << 0)
	cloudRoleUpdateFieldRoleArn                = big.NewInt(1 << 1)
	cloudRoleUpdateFieldSessionDurationSeconds = big.NewInt(1 << 2)
	cloudRoleUpdateFieldIsEnabled              = big.NewInt(1 << 3)
)

type CloudRoleUpdate struct {
	RoleID                 string  `json:"-" url:"-"`
	RoleArn                *string `json:"role_arn,omitempty" url:"-"`
	SessionDurationSeconds *int    `json:"session_duration_seconds,omitempty" url:"-"`
	IsEnabled              *bool   `json:"is_enabled,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CloudRoleUpdate) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetRoleID sets the RoleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleUpdate) SetRoleID(roleID string) {
	c.RoleID = roleID
	c.require(cloudRoleUpdateFieldRoleID)
}

// SetRoleArn sets the RoleArn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleUpdate) SetRoleArn(roleArn *string) {
	c.RoleArn = roleArn
	c.require(cloudRoleUpdateFieldRoleArn)
}

// SetSessionDurationSeconds sets the SessionDurationSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleUpdate) SetSessionDurationSeconds(sessionDurationSeconds *int) {
	c.SessionDurationSeconds = sessionDurationSeconds
	c.require(cloudRoleUpdateFieldSessionDurationSeconds)
}

// SetIsEnabled sets the IsEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CloudRoleUpdate) SetIsEnabled(isEnabled *bool) {
	c.IsEnabled = isEnabled
	c.require(cloudRoleUpdateFieldIsEnabled)
}

func (c *CloudRoleUpdate) UnmarshalJSON(data []byte) error {
	type unmarshaler CloudRoleUpdate
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CloudRoleUpdate(body)
	return nil
}

func (c *CloudRoleUpdate) MarshalJSON() ([]byte, error) {
	type embed CloudRoleUpdate
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}
