// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
	big "math/big"
)

var (
	creditBalanceFieldBalanceCents = big.NewInt(1 << 0)
	creditBalanceFieldCurrency     = big.NewInt(1 << 1)
)

type CreditBalance struct {
	// Available credit balance in cents of the returned currency.
	BalanceCents int `json:"balance_cents" url:"balance_cents"`
	// ISO 4217 currency code.
	Currency *string `json:"currency,omitempty" url:"currency,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreditBalance) GetBalanceCents() int {
	if c == nil {
		return 0
	}
	return c.BalanceCents
}

func (c *CreditBalance) GetCurrency() *string {
	if c == nil {
		return nil
	}
	return c.Currency
}

func (c *CreditBalance) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreditBalance) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetBalanceCents sets the BalanceCents field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditBalance) SetBalanceCents(balanceCents int) {
	c.BalanceCents = balanceCents
	c.require(creditBalanceFieldBalanceCents)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditBalance) SetCurrency(currency *string) {
	c.Currency = currency
	c.require(creditBalanceFieldCurrency)
}

func (c *CreditBalance) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditBalance
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditBalance(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditBalance) MarshalJSON() ([]byte, error) {
	type embed CreditBalance
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreditBalance) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
