// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	big "math/big"
)

var (
	askFactoryLineRunRequestFieldRunID = big.NewInt(1 << 0)
)

type AskFactoryLineRunRequest struct {
	RunID string             `json:"-" url:"-"`
	Body  *LineRunAskRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AskFactoryLineRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AskFactoryLineRunRequest) SetRunID(runID string) {
	a.RunID = runID
	a.require(askFactoryLineRunRequestFieldRunID)
}

func (a *AskFactoryLineRunRequest) UnmarshalJSON(data []byte) error {
	body := new(LineRunAskRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	a.Body = body
	return nil
}

func (a *AskFactoryLineRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.Body)
}

var (
	cancelFactoryLineRunRequestFieldRunID = big.NewInt(1 << 0)
)

type CancelFactoryLineRunRequest struct {
	RunID string                 `json:"-" url:"-"`
	Body  *LineRunControlRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CancelFactoryLineRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CancelFactoryLineRunRequest) SetRunID(runID string) {
	c.RunID = runID
	c.require(cancelFactoryLineRunRequestFieldRunID)
}

func (c *CancelFactoryLineRunRequest) UnmarshalJSON(data []byte) error {
	body := new(LineRunControlRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CancelFactoryLineRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	deleteFactoryLineRequestFieldName = big.NewInt(1 << 0)
)

type DeleteFactoryLineRequest struct {
	Name string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteFactoryLineRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFactoryLineRequest) SetName(name string) {
	d.Name = name
	d.require(deleteFactoryLineRequestFieldName)
}

var (
	deleteFactoryLineScheduleRequestFieldName = big.NewInt(1 << 0)
)

type DeleteFactoryLineScheduleRequest struct {
	Name string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteFactoryLineScheduleRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFactoryLineScheduleRequest) SetName(name string) {
	d.Name = name
	d.require(deleteFactoryLineScheduleRequestFieldName)
}

var (
	deployFactoryLineRequestFieldName = big.NewInt(1 << 0)
)

type DeployFactoryLineRequest struct {
	Name string             `json:"-" url:"-"`
	Body *LineDeployRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeployFactoryLineRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeployFactoryLineRequest) SetName(name string) {
	d.Name = name
	d.require(deployFactoryLineRequestFieldName)
}

func (d *DeployFactoryLineRequest) UnmarshalJSON(data []byte) error {
	body := new(LineDeployRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	d.Body = body
	return nil
}

func (d *DeployFactoryLineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Body)
}

var (
	getFactoryLineRequestFieldName = big.NewInt(1 << 0)
)

type GetFactoryLineRequest struct {
	Name string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFactoryLineRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFactoryLineRequest) SetName(name string) {
	g.Name = name
	g.require(getFactoryLineRequestFieldName)
}

var (
	getFactoryLineRunRequestFieldRunID = big.NewInt(1 << 0)
)

type GetFactoryLineRunRequest struct {
	RunID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFactoryLineRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFactoryLineRunRequest) SetRunID(runID string) {
	g.RunID = runID
	g.require(getFactoryLineRunRequestFieldRunID)
}

var (
	getFactoryLineRunDebugRequestFieldRunID = big.NewInt(1 << 0)
)

type GetFactoryLineRunDebugRequest struct {
	RunID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFactoryLineRunDebugRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFactoryLineRunDebugRequest) SetRunID(runID string) {
	g.RunID = runID
	g.require(getFactoryLineRunDebugRequestFieldRunID)
}

var (
	getFactoryLineScheduleRequestFieldName = big.NewInt(1 << 0)
)

type GetFactoryLineScheduleRequest struct {
	Name string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFactoryLineScheduleRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFactoryLineScheduleRequest) SetName(name string) {
	g.Name = name
	g.require(getFactoryLineScheduleRequestFieldName)
}

var (
	listFactoryLineRunEventsRequestFieldRunID      = big.NewInt(1 << 0)
	listFactoryLineRunEventsRequestFieldLimit      = big.NewInt(1 << 1)
	listFactoryLineRunEventsRequestFieldOffset     = big.NewInt(1 << 2)
	listFactoryLineRunEventsRequestFieldEventTypes = big.NewInt(1 << 3)
)

type ListFactoryLineRunEventsRequest struct {
	RunID  string `json:"-" url:"-"`
	Limit  *int   `json:"-" url:"limit,omitempty"`
	Offset *int   `json:"-" url:"offset,omitempty"`
	// Restrict the timeline to these event types
	EventTypes []string `json:"-" url:"event_types,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFactoryLineRunEventsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunEventsRequest) SetRunID(runID string) {
	l.RunID = runID
	l.require(listFactoryLineRunEventsRequestFieldRunID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunEventsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFactoryLineRunEventsRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunEventsRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listFactoryLineRunEventsRequestFieldOffset)
}

// SetEventTypes sets the EventTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunEventsRequest) SetEventTypes(eventTypes []string) {
	l.EventTypes = eventTypes
	l.require(listFactoryLineRunEventsRequestFieldEventTypes)
}

var (
	listFactoryLineRunFacetsRequestFieldFields    = big.NewInt(1 << 0)
	listFactoryLineRunFacetsRequestFieldStatus    = big.NewInt(1 << 1)
	listFactoryLineRunFacetsRequestFieldLineName  = big.NewInt(1 << 2)
	listFactoryLineRunFacetsRequestFieldCreatedAt = big.NewInt(1 << 3)
	listFactoryLineRunFacetsRequestFieldQ         = big.NewInt(1 << 4)
)

type ListFactoryLineRunFacetsRequest struct {
	// Facet fields to return (e.g. line_name, status)
	Fields   []*string `json:"-" url:"fields,omitempty"`
	Status   []*string `json:"-" url:"status,omitempty"`
	LineName []*string `json:"-" url:"line_name,omitempty"`
	// created_at range. Operators: gte, gt, lte, lt. Serialized as created_at[gte]=…&created_at[lt]=…
	CreatedAt *TimestampRange `json:"-" url:"created_at,omitempty"`
	Q         *string         `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFactoryLineRunFacetsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunFacetsRequest) SetFields(fields []*string) {
	l.Fields = fields
	l.require(listFactoryLineRunFacetsRequestFieldFields)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunFacetsRequest) SetStatus(status []*string) {
	l.Status = status
	l.require(listFactoryLineRunFacetsRequestFieldStatus)
}

// SetLineName sets the LineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunFacetsRequest) SetLineName(lineName []*string) {
	l.LineName = lineName
	l.require(listFactoryLineRunFacetsRequestFieldLineName)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunFacetsRequest) SetCreatedAt(createdAt *TimestampRange) {
	l.CreatedAt = createdAt
	l.require(listFactoryLineRunFacetsRequestFieldCreatedAt)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunFacetsRequest) SetQ(q *string) {
	l.Q = q
	l.require(listFactoryLineRunFacetsRequestFieldQ)
}

var (
	listFactoryLineRunsRequestFieldLimit     = big.NewInt(1 << 0)
	listFactoryLineRunsRequestFieldOffset    = big.NewInt(1 << 1)
	listFactoryLineRunsRequestFieldCursor    = big.NewInt(1 << 2)
	listFactoryLineRunsRequestFieldSort      = big.NewInt(1 << 3)
	listFactoryLineRunsRequestFieldInclude   = big.NewInt(1 << 4)
	listFactoryLineRunsRequestFieldStatus    = big.NewInt(1 << 5)
	listFactoryLineRunsRequestFieldLineName  = big.NewInt(1 << 6)
	listFactoryLineRunsRequestFieldCreatedAt = big.NewInt(1 << 7)
	listFactoryLineRunsRequestFieldQ         = big.NewInt(1 << 8)
)

type ListFactoryLineRunsRequest struct {
	Limit  *int    `json:"-" url:"limit,omitempty"`
	Offset *int    `json:"-" url:"offset,omitempty"`
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Sort order. Allowed: -created_at, created_at
	Sort     *string   `json:"-" url:"sort,omitempty"`
	Include  []*string `json:"-" url:"include,omitempty"`
	Status   []*string `json:"-" url:"status,omitempty"`
	LineName []*string `json:"-" url:"line_name,omitempty"`
	// created_at range. Operators: gte, gt, lte, lt. Serialized as created_at[gte]=…&created_at[lt]=…
	CreatedAt *TimestampRange `json:"-" url:"created_at,omitempty"`
	Q         *string         `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFactoryLineRunsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFactoryLineRunsRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listFactoryLineRunsRequestFieldOffset)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listFactoryLineRunsRequestFieldCursor)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetSort(sort *string) {
	l.Sort = sort
	l.require(listFactoryLineRunsRequestFieldSort)
}

// SetInclude sets the Include field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetInclude(include []*string) {
	l.Include = include
	l.require(listFactoryLineRunsRequestFieldInclude)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetStatus(status []*string) {
	l.Status = status
	l.require(listFactoryLineRunsRequestFieldStatus)
}

// SetLineName sets the LineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetLineName(lineName []*string) {
	l.LineName = lineName
	l.require(listFactoryLineRunsRequestFieldLineName)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetCreatedAt(createdAt *TimestampRange) {
	l.CreatedAt = createdAt
	l.require(listFactoryLineRunsRequestFieldCreatedAt)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsRequest) SetQ(q *string) {
	l.Q = q
	l.require(listFactoryLineRunsRequestFieldQ)
}

var (
	listFactoryLineRunsForLineRequestFieldName   = big.NewInt(1 << 0)
	listFactoryLineRunsForLineRequestFieldLimit  = big.NewInt(1 << 1)
	listFactoryLineRunsForLineRequestFieldOffset = big.NewInt(1 << 2)
)

type ListFactoryLineRunsForLineRequest struct {
	Name   string `json:"-" url:"-"`
	Limit  *int   `json:"-" url:"limit,omitempty"`
	Offset *int   `json:"-" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFactoryLineRunsForLineRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsForLineRequest) SetName(name string) {
	l.Name = name
	l.require(listFactoryLineRunsForLineRequestFieldName)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsForLineRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFactoryLineRunsForLineRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineRunsForLineRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listFactoryLineRunsForLineRequestFieldOffset)
}

var (
	listFactoryLineVersionsRequestFieldName   = big.NewInt(1 << 0)
	listFactoryLineVersionsRequestFieldLimit  = big.NewInt(1 << 1)
	listFactoryLineVersionsRequestFieldOffset = big.NewInt(1 << 2)
)

type ListFactoryLineVersionsRequest struct {
	Name   string `json:"-" url:"-"`
	Limit  *int   `json:"-" url:"limit,omitempty"`
	Offset *int   `json:"-" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFactoryLineVersionsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineVersionsRequest) SetName(name string) {
	l.Name = name
	l.require(listFactoryLineVersionsRequestFieldName)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineVersionsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFactoryLineVersionsRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLineVersionsRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listFactoryLineVersionsRequestFieldOffset)
}

var (
	listFactoryLinesRequestFieldLimit  = big.NewInt(1 << 0)
	listFactoryLinesRequestFieldOffset = big.NewInt(1 << 1)
)

type ListFactoryLinesRequest struct {
	Limit  *int `json:"-" url:"limit,omitempty"`
	Offset *int `json:"-" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFactoryLinesRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLinesRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listFactoryLinesRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFactoryLinesRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listFactoryLinesRequestFieldOffset)
}

var (
	retryFactoryLineRunRequestFieldRunID = big.NewInt(1 << 0)
)

type RetryFactoryLineRunRequest struct {
	RunID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetryFactoryLineRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetryFactoryLineRunRequest) SetRunID(runID string) {
	r.RunID = runID
	r.require(retryFactoryLineRunRequestFieldRunID)
}

var (
	steerFactoryLineRunRequestFieldRunID = big.NewInt(1 << 0)
)

type SteerFactoryLineRunRequest struct {
	RunID string               `json:"-" url:"-"`
	Body  *LineRunSteerRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SteerFactoryLineRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if s.explicitFields != nil {
		next.Set(s.explicitFields)
	}
	next.Or(next, field)
	s.explicitFields = next
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteerFactoryLineRunRequest) SetRunID(runID string) {
	s.RunID = runID
	s.require(steerFactoryLineRunRequestFieldRunID)
}

func (s *SteerFactoryLineRunRequest) UnmarshalJSON(data []byte) error {
	body := new(LineRunSteerRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.Body = body
	return nil
}

func (s *SteerFactoryLineRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

var (
	stopFactoryLineRunRequestFieldRunID = big.NewInt(1 << 0)
)

type StopFactoryLineRunRequest struct {
	RunID string                 `json:"-" url:"-"`
	Body  *LineRunControlRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StopFactoryLineRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if s.explicitFields != nil {
		next.Set(s.explicitFields)
	}
	next.Or(next, field)
	s.explicitFields = next
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopFactoryLineRunRequest) SetRunID(runID string) {
	s.RunID = runID
	s.require(stopFactoryLineRunRequestFieldRunID)
}

func (s *StopFactoryLineRunRequest) UnmarshalJSON(data []byte) error {
	body := new(LineRunControlRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.Body = body
	return nil
}

func (s *StopFactoryLineRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

var (
	triggerFactoryLineRunRequestFieldName = big.NewInt(1 << 0)
)

type TriggerFactoryLineRunRequest struct {
	Name string         `json:"-" url:"-"`
	Body *LineRunCreate `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TriggerFactoryLineRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if t.explicitFields != nil {
		next.Set(t.explicitFields)
	}
	next.Or(next, field)
	t.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TriggerFactoryLineRunRequest) SetName(name string) {
	t.Name = name
	t.require(triggerFactoryLineRunRequestFieldName)
}

func (t *TriggerFactoryLineRunRequest) UnmarshalJSON(data []byte) error {
	body := new(LineRunCreate)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.Body = body
	return nil
}

func (t *TriggerFactoryLineRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

var (
	updateFactoryLineRequestFieldName = big.NewInt(1 << 0)
)

type UpdateFactoryLineRequest struct {
	Name string      `json:"-" url:"-"`
	Body *LineUpdate `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateFactoryLineRequest) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateFactoryLineRequest) SetName(name string) {
	u.Name = name
	u.require(updateFactoryLineRequestFieldName)
}

func (u *UpdateFactoryLineRequest) UnmarshalJSON(data []byte) error {
	body := new(LineUpdate)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpdateFactoryLineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

var (
	upsertFactoryLineScheduleRequestFieldName = big.NewInt(1 << 0)
)

type UpsertFactoryLineScheduleRequest struct {
	Name string              `json:"-" url:"-"`
	Body *LineScheduleUpdate `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpsertFactoryLineScheduleRequest) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpsertFactoryLineScheduleRequest) SetName(name string) {
	u.Name = name
	u.require(upsertFactoryLineScheduleRequestFieldName)
}

func (u *UpsertFactoryLineScheduleRequest) UnmarshalJSON(data []byte) error {
	body := new(LineScheduleUpdate)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpsertFactoryLineScheduleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

var (
	validateFactoryLineManifestRequestFieldName = big.NewInt(1 << 0)
)

type ValidateFactoryLineManifestRequest struct {
	Name string             `json:"-" url:"-"`
	Body *LineDeployRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *ValidateFactoryLineManifestRequest) require(field *big.Int) {
	next := new(big.Int)
	if v.explicitFields != nil {
		next.Set(v.explicitFields)
	}
	next.Or(next, field)
	v.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidateFactoryLineManifestRequest) SetName(name string) {
	v.Name = name
	v.require(validateFactoryLineManifestRequestFieldName)
}

func (v *ValidateFactoryLineManifestRequest) UnmarshalJSON(data []byte) error {
	body := new(LineDeployRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	v.Body = body
	return nil
}

func (v *ValidateFactoryLineManifestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Body)
}
