// Code generated by Fern. DO NOT EDIT.

package api

type GetGatewayPolicyByKeyRequest struct {
	SandboxID      *string `json:"-" url:"-"`
	IfNoneMatch    *string `json:"-" url:"-"`
	PublicTenantID *string `json:"-" url:"-"`
	PublicUserID   *string `json:"-" url:"-"`
	ProfileKey     string  `json:"-" url:"-"`
}

type GetGatewayTokenRequest struct {
	PublicTenantID *string `json:"-" url:"-"`
	PublicUserID   *string `json:"-" url:"-"`
	SandboxID      *string `json:"-" url:"-"`
	ProviderKey    string  `json:"-" url:"provider_key"`
}

type GetSandboxPolicyRequest struct {
	IfNoneMatch    *string `json:"-" url:"-"`
	PublicTenantID *string `json:"-" url:"-"`
	PublicUserID   *string `json:"-" url:"-"`
	SandboxID      *string `json:"-" url:"-"`
	SandboxID      string  `json:"-" url:"-"`
}
