// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
)

type CustomServiceCreateRequest struct {
	Custom *CustomIntegration `json:"custom,omitempty" url:"-"`
}

type DisconnectCustomIntegrationRequest struct {
	DescopeAppID string `json:"-" url:"-"`
	// Which token to revoke: 'user' (this user's personal) or 'tenant' (workspace)
	Scope *IntegrationLevel `json:"-" url:"scope,omitempty"`
	// Also remove the Descope outbound app entirely (affects every user in this workspace)
	DeleteApp *bool `json:"-" url:"delete_app,omitempty"`
}

type DisconnectIntegrationRequest struct {
	Provider string            `json:"-" url:"-"`
	Level    *IntegrationLevel `json:"-" url:"level,omitempty"`
	// oauth or api_key
	AuthType *AuthMethod `json:"-" url:"auth_type,omitempty"`
}

type GetIntegrationStatusRequest struct {
	Provider string `json:"-" url:"-"`
}

// Shape of the Descope outbound app backing this integration.
//
// Limited to the two underlying Descope app types: “OAUTH“ (oidc) and
// “API_KEY“ (custom_api_key). The injection style for an API-key
// integration (bearer / basic / custom header) is configured on the
// GatewayRule, not the integration itself, so any number of rules can
// re-use the same stored credential with different injection conventions.
type AuthMethod string

const (
	AuthMethodOauth  AuthMethod = "oauth"
	AuthMethodAPIKey AuthMethod = "api_key"
)

func NewAuthMethodFromString(s string) (AuthMethod, error) {
	switch s {
	case "oauth":
		return AuthMethodOauth, nil
	case "api_key":
		return AuthMethodAPIKey, nil
	}
	var t AuthMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AuthMethod) Ptr() *AuthMethod {
	return &a
}

// Connection status for a single level (user or tenant).
type ConnectionStatus struct {
	Connected   bool     `json:"connected" url:"connected"`
	ConnectedAt *string  `json:"connected_at,omitempty" url:"connected_at,omitempty"`
	Username    *string  `json:"username,omitempty" url:"username,omitempty"`
	Email       *string  `json:"email,omitempty" url:"email,omitempty"`
	Scopes      []string `json:"scopes,omitempty" url:"scopes,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectionStatus) GetConnected() bool {
	if c == nil {
		return false
	}
	return c.Connected
}

func (c *ConnectionStatus) GetConnectedAt() *string {
	if c == nil {
		return nil
	}
	return c.ConnectedAt
}

func (c *ConnectionStatus) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *ConnectionStatus) GetEmail() *string {
	if c == nil {
		return nil
	}
	return c.Email
}

func (c *ConnectionStatus) GetScopes() []string {
	if c == nil {
		return nil
	}
	return c.Scopes
}

func (c *ConnectionStatus) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ConnectionStatus) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectionStatus
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectionStatus(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectionStatus) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Tenant-scoped custom integration spec.
//
// The frontend owns slug derivation (live preview matches what's stored).
// The backend treats “slug“ as authoritative input and only validates its
// shape -- it never re-derives. “name“ is the free-form human label and
// is allowed to contain anything reasonable.
type CustomIntegration struct {
	Name             string      `json:"name" url:"name"`
	Slug             string      `json:"slug" url:"slug"`
	McpURL           *string     `json:"mcp_url,omitempty" url:"mcp_url,omitempty"`
	AuthMethod       *AuthMethod `json:"auth_method,omitempty" url:"auth_method,omitempty"`
	ClientID         *string     `json:"client_id,omitempty" url:"client_id,omitempty"`
	ClientSecret     *string     `json:"client_secret,omitempty" url:"client_secret,omitempty"`
	AuthorizationURL *string     `json:"authorization_url,omitempty" url:"authorization_url,omitempty"`
	TokenURL         *string     `json:"token_url,omitempty" url:"token_url,omitempty"`
	Scopes           []string    `json:"scopes,omitempty" url:"scopes,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomIntegration) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomIntegration) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

func (c *CustomIntegration) GetMcpURL() *string {
	if c == nil {
		return nil
	}
	return c.McpURL
}

func (c *CustomIntegration) GetAuthMethod() *AuthMethod {
	if c == nil {
		return nil
	}
	return c.AuthMethod
}

func (c *CustomIntegration) GetClientID() *string {
	if c == nil {
		return nil
	}
	return c.ClientID
}

func (c *CustomIntegration) GetClientSecret() *string {
	if c == nil {
		return nil
	}
	return c.ClientSecret
}

func (c *CustomIntegration) GetAuthorizationURL() *string {
	if c == nil {
		return nil
	}
	return c.AuthorizationURL
}

func (c *CustomIntegration) GetTokenURL() *string {
	if c == nil {
		return nil
	}
	return c.TokenURL
}

func (c *CustomIntegration) GetScopes() []string {
	if c == nil {
		return nil
	}
	return c.Scopes
}

func (c *CustomIntegration) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomIntegration) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomIntegration
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomIntegration(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomIntegration) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Tenant-wide custom integration metadata for the Add Integration picker.
//
// “name“ is the free-form display label; “slug“ is the normalized
// identifier embedded in “descope_app_id“ and used as “provider_key“
// in gateway rules.
type CustomService struct {
	DescopeAppID string     `json:"descope_app_id" url:"descope_app_id"`
	Name         string     `json:"name" url:"name"`
	Slug         string     `json:"slug" url:"slug"`
	AuthMethod   AuthMethod `json:"auth_method" url:"auth_method"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomService) GetDescopeAppID() string {
	if c == nil {
		return ""
	}
	return c.DescopeAppID
}

func (c *CustomService) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomService) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

func (c *CustomService) GetAuthMethod() AuthMethod {
	if c == nil {
		return ""
	}
	return c.AuthMethod
}

func (c *CustomService) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomService) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomService
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomService(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomService) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Newly created custom service descriptor.
//
// Mirrors the fields the modal needs to immediately kick off the connect
// flow (OAuth) or surface the API key form, without re-fetching.
type CustomServiceCreateResponse struct {
	AppID      string     `json:"app_id" url:"app_id"`
	Name       string     `json:"name" url:"name"`
	Slug       string     `json:"slug" url:"slug"`
	AuthMethod AuthMethod `json:"auth_method" url:"auth_method"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomServiceCreateResponse) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *CustomServiceCreateResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomServiceCreateResponse) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

func (c *CustomServiceCreateResponse) GetAuthMethod() AuthMethod {
	if c == nil {
		return ""
	}
	return c.AuthMethod
}

func (c *CustomServiceCreateResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomServiceCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomServiceCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomServiceCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomServiceCreateResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// List of custom services defined in the current tenant.
type CustomServicesResponse struct {
	Services []*CustomService `json:"services" url:"services"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomServicesResponse) GetServices() []*CustomService {
	if c == nil {
		return nil
	}
	return c.Services
}

func (c *CustomServicesResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomServicesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomServicesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomServicesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomServicesResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Detailed status of an integration showing both user and tenant levels.
type IntegrationDetailResponse struct {
	Provider string            `json:"provider" url:"provider"`
	User     *ConnectionStatus `json:"user" url:"user"`
	Tenant   *ConnectionStatus `json:"tenant" url:"tenant"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntegrationDetailResponse) GetProvider() string {
	if i == nil {
		return ""
	}
	return i.Provider
}

func (i *IntegrationDetailResponse) GetUser() *ConnectionStatus {
	if i == nil {
		return nil
	}
	return i.User
}

func (i *IntegrationDetailResponse) GetTenant() *ConnectionStatus {
	if i == nil {
		return nil
	}
	return i.Tenant
}

func (i *IntegrationDetailResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntegrationDetailResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler IntegrationDetailResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntegrationDetailResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntegrationDetailResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Level at which an integration is installed.
type IntegrationLevel string

const (
	IntegrationLevelUser   IntegrationLevel = "user"
	IntegrationLevelTenant IntegrationLevel = "tenant"
)

func NewIntegrationLevelFromString(s string) (IntegrationLevel, error) {
	switch s {
	case "user":
		return IntegrationLevelUser, nil
	case "tenant":
		return IntegrationLevelTenant, nil
	}
	var t IntegrationLevel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IntegrationLevel) Ptr() *IntegrationLevel {
	return &i
}

// List of integrations (both user and tenant level).
type IntegrationListResponse struct {
	Integrations []*IntegrationStatus `json:"integrations" url:"integrations"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntegrationListResponse) GetIntegrations() []*IntegrationStatus {
	if i == nil {
		return nil
	}
	return i.Integrations
}

func (i *IntegrationListResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntegrationListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler IntegrationListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntegrationListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntegrationListResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Information about an available provider.
type IntegrationProvider struct {
	Name  string         `json:"name" url:"name"`
	Hosts []string       `json:"hosts" url:"hosts"`
	Apps  []*ProviderApp `json:"apps" url:"apps"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntegrationProvider) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IntegrationProvider) GetHosts() []string {
	if i == nil {
		return nil
	}
	return i.Hosts
}

func (i *IntegrationProvider) GetApps() []*ProviderApp {
	if i == nil {
		return nil
	}
	return i.Apps
}

func (i *IntegrationProvider) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntegrationProvider) UnmarshalJSON(data []byte) error {
	type unmarshaler IntegrationProvider
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntegrationProvider(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntegrationProvider) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// List of available integration providers.
type IntegrationProvidersResponse struct {
	Providers []*IntegrationProvider `json:"providers" url:"providers"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntegrationProvidersResponse) GetProviders() []*IntegrationProvider {
	if i == nil {
		return nil
	}
	return i.Providers
}

func (i *IntegrationProvidersResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntegrationProvidersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler IntegrationProvidersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntegrationProvidersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntegrationProvidersResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Status of a single integration (for list view).
//
// “provider“ is the stable identifier (preset id or custom slug).
// “display_name“ carries the human-readable label for customs (the
// free-form text the creator typed); presets surface their static name
// via the frontend's preset catalog so this stays None for them.
type IntegrationStatus struct {
	Provider     string            `json:"provider" url:"provider"`
	Connected    bool              `json:"connected" url:"connected"`
	Level        *IntegrationLevel `json:"level,omitempty" url:"level,omitempty"`
	AuthMethod   *AuthMethod       `json:"auth_method,omitempty" url:"auth_method,omitempty"`
	DescopeAppID *string           `json:"descope_app_id,omitempty" url:"descope_app_id,omitempty"`
	PresetID     *string           `json:"preset_id,omitempty" url:"preset_id,omitempty"`
	DisplayName  *string           `json:"display_name,omitempty" url:"display_name,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntegrationStatus) GetProvider() string {
	if i == nil {
		return ""
	}
	return i.Provider
}

func (i *IntegrationStatus) GetConnected() bool {
	if i == nil {
		return false
	}
	return i.Connected
}

func (i *IntegrationStatus) GetLevel() *IntegrationLevel {
	if i == nil {
		return nil
	}
	return i.Level
}

func (i *IntegrationStatus) GetAuthMethod() *AuthMethod {
	if i == nil {
		return nil
	}
	return i.AuthMethod
}

func (i *IntegrationStatus) GetDescopeAppID() *string {
	if i == nil {
		return nil
	}
	return i.DescopeAppID
}

func (i *IntegrationStatus) GetPresetID() *string {
	if i == nil {
		return nil
	}
	return i.PresetID
}

func (i *IntegrationStatus) GetDisplayName() *string {
	if i == nil {
		return nil
	}
	return i.DisplayName
}

func (i *IntegrationStatus) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntegrationStatus) UnmarshalJSON(data []byte) error {
	type unmarshaler IntegrationStatus
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntegrationStatus(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntegrationStatus) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// A single Descope outbound app backing one (auth_method, scope) combo.
//
// Presets pre-provision up to four Descope outbound apps, one per
// “auth_method“ x “scope“ combination they support. Shipping them
// on “GET /integrations/providers“ lets the frontend resolve the right
// “app_id“ locally and skip a server round-trip on the connect path.
type ProviderApp struct {
	AuthMethod AuthMethod       `json:"auth_method" url:"auth_method"`
	Scope      IntegrationLevel `json:"scope" url:"scope"`
	AppID      string           `json:"app_id" url:"app_id"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProviderApp) GetAuthMethod() AuthMethod {
	if p == nil {
		return ""
	}
	return p.AuthMethod
}

func (p *ProviderApp) GetScope() IntegrationLevel {
	if p == nil {
		return ""
	}
	return p.Scope
}

func (p *ProviderApp) GetAppID() string {
	if p == nil {
		return ""
	}
	return p.AppID
}

func (p *ProviderApp) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *ProviderApp) UnmarshalJSON(data []byte) error {
	type unmarshaler ProviderApp
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProviderApp(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProviderApp) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
