// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	big "math/big"
)

var (
	deleteJobRequestFieldName = big.NewInt(1 << 0)
)

type DeleteJobRequest struct {
	Name string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteJobRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteJobRequest) SetName(name string) {
	d.Name = name
	d.require(deleteJobRequestFieldName)
}

var (
	deleteJobScheduleRequestFieldName = big.NewInt(1 << 0)
)

type DeleteJobScheduleRequest struct {
	Name string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteJobScheduleRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteJobScheduleRequest) SetName(name string) {
	d.Name = name
	d.require(deleteJobScheduleRequestFieldName)
}

var (
	deployJobRequestFieldName = big.NewInt(1 << 0)
)

type DeployJobRequest struct {
	Name string            `json:"-" url:"-"`
	Body *JobDeployRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeployJobRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeployJobRequest) SetName(name string) {
	d.Name = name
	d.require(deployJobRequestFieldName)
}

func (d *DeployJobRequest) UnmarshalJSON(data []byte) error {
	body := new(JobDeployRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	d.Body = body
	return nil
}

func (d *DeployJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Body)
}

var (
	getJobRequestFieldName = big.NewInt(1 << 0)
)

type GetJobRequest struct {
	Name string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetJobRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetJobRequest) SetName(name string) {
	g.Name = name
	g.require(getJobRequestFieldName)
}

var (
	getJobRunRequestFieldName  = big.NewInt(1 << 0)
	getJobRunRequestFieldRunID = big.NewInt(1 << 1)
)

type GetJobRunRequest struct {
	Name  string `json:"-" url:"-"`
	RunID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetJobRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetJobRunRequest) SetName(name string) {
	g.Name = name
	g.require(getJobRunRequestFieldName)
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetJobRunRequest) SetRunID(runID string) {
	g.RunID = runID
	g.require(getJobRunRequestFieldRunID)
}

var (
	getJobScheduleRequestFieldName = big.NewInt(1 << 0)
)

type GetJobScheduleRequest struct {
	Name string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetJobScheduleRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetJobScheduleRequest) SetName(name string) {
	g.Name = name
	g.require(getJobScheduleRequestFieldName)
}

var (
	getJobVersionRequestFieldName      = big.NewInt(1 << 0)
	getJobVersionRequestFieldVersionID = big.NewInt(1 << 1)
)

type GetJobVersionRequest struct {
	Name      string `json:"-" url:"-"`
	VersionID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetJobVersionRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetJobVersionRequest) SetName(name string) {
	g.Name = name
	g.require(getJobVersionRequestFieldName)
}

// SetVersionID sets the VersionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetJobVersionRequest) SetVersionID(versionID string) {
	g.VersionID = versionID
	g.require(getJobVersionRequestFieldVersionID)
}

var (
	listJobRunsRequestFieldName   = big.NewInt(1 << 0)
	listJobRunsRequestFieldLimit  = big.NewInt(1 << 1)
	listJobRunsRequestFieldOffset = big.NewInt(1 << 2)
)

type ListJobRunsRequest struct {
	Name   string `json:"-" url:"-"`
	Limit  *int   `json:"-" url:"limit,omitempty"`
	Offset *int   `json:"-" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListJobRunsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListJobRunsRequest) SetName(name string) {
	l.Name = name
	l.require(listJobRunsRequestFieldName)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListJobRunsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listJobRunsRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListJobRunsRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listJobRunsRequestFieldOffset)
}

var (
	listJobVersionsRequestFieldName   = big.NewInt(1 << 0)
	listJobVersionsRequestFieldLimit  = big.NewInt(1 << 1)
	listJobVersionsRequestFieldOffset = big.NewInt(1 << 2)
)

type ListJobVersionsRequest struct {
	Name   string `json:"-" url:"-"`
	Limit  *int   `json:"-" url:"limit,omitempty"`
	Offset *int   `json:"-" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListJobVersionsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListJobVersionsRequest) SetName(name string) {
	l.Name = name
	l.require(listJobVersionsRequestFieldName)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListJobVersionsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listJobVersionsRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListJobVersionsRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listJobVersionsRequestFieldOffset)
}

var (
	listJobsRequestFieldLimit  = big.NewInt(1 << 0)
	listJobsRequestFieldOffset = big.NewInt(1 << 1)
)

type ListJobsRequest struct {
	Limit  *int `json:"-" url:"limit,omitempty"`
	Offset *int `json:"-" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListJobsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListJobsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listJobsRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListJobsRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listJobsRequestFieldOffset)
}

var (
	stopJobRunRequestFieldName  = big.NewInt(1 << 0)
	stopJobRunRequestFieldRunID = big.NewInt(1 << 1)
)

type StopJobRunRequest struct {
	Name  string             `json:"-" url:"-"`
	RunID string             `json:"-" url:"-"`
	Body  *JobRunStopRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StopJobRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if s.explicitFields != nil {
		next.Set(s.explicitFields)
	}
	next.Or(next, field)
	s.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopJobRunRequest) SetName(name string) {
	s.Name = name
	s.require(stopJobRunRequestFieldName)
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopJobRunRequest) SetRunID(runID string) {
	s.RunID = runID
	s.require(stopJobRunRequestFieldRunID)
}

func (s *StopJobRunRequest) UnmarshalJSON(data []byte) error {
	body := new(JobRunStopRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.Body = body
	return nil
}

func (s *StopJobRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

var (
	triggerJobRunRequestFieldName = big.NewInt(1 << 0)
)

type TriggerJobRunRequest struct {
	Name string        `json:"-" url:"-"`
	Body *JobRunCreate `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TriggerJobRunRequest) require(field *big.Int) {
	next := new(big.Int)
	if t.explicitFields != nil {
		next.Set(t.explicitFields)
	}
	next.Or(next, field)
	t.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TriggerJobRunRequest) SetName(name string) {
	t.Name = name
	t.require(triggerJobRunRequestFieldName)
}

func (t *TriggerJobRunRequest) UnmarshalJSON(data []byte) error {
	body := new(JobRunCreate)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.Body = body
	return nil
}

func (t *TriggerJobRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

var (
	validateJobManifestRequestFieldName = big.NewInt(1 << 0)
)

type ValidateJobManifestRequest struct {
	Name string            `json:"-" url:"-"`
	Body *JobDeployRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *ValidateJobManifestRequest) require(field *big.Int) {
	next := new(big.Int)
	if v.explicitFields != nil {
		next.Set(v.explicitFields)
	}
	next.Or(next, field)
	v.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidateJobManifestRequest) SetName(name string) {
	v.Name = name
	v.require(validateJobManifestRequestFieldName)
}

func (v *ValidateJobManifestRequest) UnmarshalJSON(data []byte) error {
	body := new(JobDeployRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	v.Body = body
	return nil
}

func (v *ValidateJobManifestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Body)
}
