// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
	time "time"
)

type DeleteJobScheduleRequest struct {
	Name string `json:"-" url:"-"`
}

type DeployJobRequest struct {
	Name string            `json:"-" url:"-"`
	Body *JobDeployRequest `json:"-" url:"-"`
}

func (d *DeployJobRequest) UnmarshalJSON(data []byte) error {
	body := new(JobDeployRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	d.Body = body
	return nil
}

func (d *DeployJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Body)
}

type GetJobRequest struct {
	Name string `json:"-" url:"-"`
}

type GetJobRunRequest struct {
	Name  string `json:"-" url:"-"`
	RunID string `json:"-" url:"-"`
}

type GetJobScheduleRequest struct {
	Name string `json:"-" url:"-"`
}

type GetJobVersionRequest struct {
	Name      string `json:"-" url:"-"`
	VersionID string `json:"-" url:"-"`
}

type ListJobRunsRequest struct {
	Name   string `json:"-" url:"-"`
	Limit  *int   `json:"-" url:"limit,omitempty"`
	Offset *int   `json:"-" url:"offset,omitempty"`
}

type ListJobVersionsRequest struct {
	Name   string `json:"-" url:"-"`
	Limit  *int   `json:"-" url:"limit,omitempty"`
	Offset *int   `json:"-" url:"offset,omitempty"`
}

type ListJobsRequest struct {
	Limit  *int `json:"-" url:"limit,omitempty"`
	Offset *int `json:"-" url:"offset,omitempty"`
}

type JobRunCreate struct {
	Name string `json:"-" url:"-"`
	// Deployed version to run; defaults to latest
	VersionID *string `json:"version_id,omitempty" url:"-"`
	// Compute region override
	Region *string `json:"region,omitempty" url:"-"`
	// Run-time parameter values (validated against [job.params])
	Params map[string]interface{} `json:"params,omitempty" url:"-"`
}

type JobDeployRequest struct {
	// Parsed job.toml content as JSON object
	Manifest map[string]interface{} `json:"manifest" url:"manifest"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JobDeployRequest) GetManifest() map[string]interface{} {
	if j == nil {
		return nil
	}
	return j.Manifest
}

func (j *JobDeployRequest) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JobDeployRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler JobDeployRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*j = JobDeployRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JobDeployRequest) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

type JobListItem struct {
	ID                  string    `json:"id" url:"id"`
	Name                string    `json:"name" url:"name"`
	LatestVersionNumber *int      `json:"latest_version_number,omitempty" url:"latest_version_number,omitempty"`
	CreatedAt           time.Time `json:"created_at" url:"created_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JobListItem) GetID() string {
	if j == nil {
		return ""
	}
	return j.ID
}

func (j *JobListItem) GetName() string {
	if j == nil {
		return ""
	}
	return j.Name
}

func (j *JobListItem) GetLatestVersionNumber() *int {
	if j == nil {
		return nil
	}
	return j.LatestVersionNumber
}

func (j *JobListItem) GetCreatedAt() time.Time {
	if j == nil {
		return time.Time{}
	}
	return j.CreatedAt
}

func (j *JobListItem) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JobListItem) UnmarshalJSON(data []byte) error {
	type embed JobListItem
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*j),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*j = JobListItem(unmarshaler.embed)
	j.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JobListItem) MarshalJSON() ([]byte, error) {
	type embed JobListItem
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*j),
		CreatedAt: internal.NewDateTime(j.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (j *JobListItem) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

type JobParamDefinition struct {
	Name string `json:"name" url:"name"`
	// string | integer | number | boolean
	Type        string        `json:"type" url:"type"`
	Required    *bool         `json:"required,omitempty" url:"required,omitempty"`
	Default     interface{}   `json:"default,omitempty" url:"default,omitempty"`
	Description *string       `json:"description,omitempty" url:"description,omitempty"`
	Pattern     *string       `json:"pattern,omitempty" url:"pattern,omitempty"`
	Prefix      *string       `json:"prefix,omitempty" url:"prefix,omitempty"`
	Enum        []interface{} `json:"enum,omitempty" url:"enum,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JobParamDefinition) GetName() string {
	if j == nil {
		return ""
	}
	return j.Name
}

func (j *JobParamDefinition) GetType() string {
	if j == nil {
		return ""
	}
	return j.Type
}

func (j *JobParamDefinition) GetRequired() *bool {
	if j == nil {
		return nil
	}
	return j.Required
}

func (j *JobParamDefinition) GetDefault() interface{} {
	if j == nil {
		return nil
	}
	return j.Default
}

func (j *JobParamDefinition) GetDescription() *string {
	if j == nil {
		return nil
	}
	return j.Description
}

func (j *JobParamDefinition) GetPattern() *string {
	if j == nil {
		return nil
	}
	return j.Pattern
}

func (j *JobParamDefinition) GetPrefix() *string {
	if j == nil {
		return nil
	}
	return j.Prefix
}

func (j *JobParamDefinition) GetEnum() []interface{} {
	if j == nil {
		return nil
	}
	return j.Enum
}

func (j *JobParamDefinition) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JobParamDefinition) UnmarshalJSON(data []byte) error {
	type unmarshaler JobParamDefinition
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*j = JobParamDefinition(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JobParamDefinition) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

type JobResponse struct {
	ID            string              `json:"id" url:"id"`
	Name          string              `json:"name" url:"name"`
	Description   *string             `json:"description,omitempty" url:"description,omitempty"`
	LatestVersion *JobVersionResponse `json:"latest_version,omitempty" url:"latest_version,omitempty"`
	// Typed run-parameter schema from the latest deployed manifest
	Params    []*JobParamDefinition `json:"params,omitempty" url:"params,omitempty"`
	CreatedAt time.Time             `json:"created_at" url:"created_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JobResponse) GetID() string {
	if j == nil {
		return ""
	}
	return j.ID
}

func (j *JobResponse) GetName() string {
	if j == nil {
		return ""
	}
	return j.Name
}

func (j *JobResponse) GetDescription() *string {
	if j == nil {
		return nil
	}
	return j.Description
}

func (j *JobResponse) GetLatestVersion() *JobVersionResponse {
	if j == nil {
		return nil
	}
	return j.LatestVersion
}

func (j *JobResponse) GetParams() []*JobParamDefinition {
	if j == nil {
		return nil
	}
	return j.Params
}

func (j *JobResponse) GetCreatedAt() time.Time {
	if j == nil {
		return time.Time{}
	}
	return j.CreatedAt
}

func (j *JobResponse) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JobResponse) UnmarshalJSON(data []byte) error {
	type embed JobResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*j),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*j = JobResponse(unmarshaler.embed)
	j.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JobResponse) MarshalJSON() ([]byte, error) {
	type embed JobResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*j),
		CreatedAt: internal.NewDateTime(j.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (j *JobResponse) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

type JobScheduleResponse struct {
	Cron               string `json:"cron" url:"cron"`
	Timezone           string `json:"timezone" url:"timezone"`
	Enabled            bool   `json:"enabled" url:"enabled"`
	ScheduleGeneration int    `json:"schedule_generation" url:"schedule_generation"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JobScheduleResponse) GetCron() string {
	if j == nil {
		return ""
	}
	return j.Cron
}

func (j *JobScheduleResponse) GetTimezone() string {
	if j == nil {
		return ""
	}
	return j.Timezone
}

func (j *JobScheduleResponse) GetEnabled() bool {
	if j == nil {
		return false
	}
	return j.Enabled
}

func (j *JobScheduleResponse) GetScheduleGeneration() int {
	if j == nil {
		return 0
	}
	return j.ScheduleGeneration
}

func (j *JobScheduleResponse) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JobScheduleResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler JobScheduleResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*j = JobScheduleResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JobScheduleResponse) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

type JobVersionResponse struct {
	ID            string                 `json:"id" url:"id"`
	VersionNumber int                    `json:"version_number" url:"version_number"`
	ContentHash   string                 `json:"content_hash" url:"content_hash"`
	DeployedAt    time.Time              `json:"deployed_at" url:"deployed_at"`
	Manifest      map[string]interface{} `json:"manifest" url:"manifest"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JobVersionResponse) GetID() string {
	if j == nil {
		return ""
	}
	return j.ID
}

func (j *JobVersionResponse) GetVersionNumber() int {
	if j == nil {
		return 0
	}
	return j.VersionNumber
}

func (j *JobVersionResponse) GetContentHash() string {
	if j == nil {
		return ""
	}
	return j.ContentHash
}

func (j *JobVersionResponse) GetDeployedAt() time.Time {
	if j == nil {
		return time.Time{}
	}
	return j.DeployedAt
}

func (j *JobVersionResponse) GetManifest() map[string]interface{} {
	if j == nil {
		return nil
	}
	return j.Manifest
}

func (j *JobVersionResponse) GetExtraProperties() map[string]interface{} {
	return j.extraProperties
}

func (j *JobVersionResponse) UnmarshalJSON(data []byte) error {
	type embed JobVersionResponse
	var unmarshaler = struct {
		embed
		DeployedAt *internal.DateTime `json:"deployed_at"`
	}{
		embed: embed(*j),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*j = JobVersionResponse(unmarshaler.embed)
	j.DeployedAt = unmarshaler.DeployedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JobVersionResponse) MarshalJSON() ([]byte, error) {
	type embed JobVersionResponse
	var marshaler = struct {
		embed
		DeployedAt *internal.DateTime `json:"deployed_at"`
	}{
		embed:      embed(*j),
		DeployedAt: internal.NewDateTime(j.DeployedAt),
	}
	return json.Marshal(marshaler)
}

func (j *JobVersionResponse) String() string {
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

type ValidateJobManifestRequest struct {
	Name string            `json:"-" url:"-"`
	Body *JobDeployRequest `json:"-" url:"-"`
}

func (v *ValidateJobManifestRequest) UnmarshalJSON(data []byte) error {
	body := new(JobDeployRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	v.Body = body
	return nil
}

func (v *ValidateJobManifestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Body)
}
