// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
)

type SandboxAttachSessionRequest struct {
	// Sandbox name
	SandboxName string `json:"-" url:"-"`
	// Session name
	Session string `json:"-" url:"-"`
}

type CreateSessionRequest struct {
	// Sandbox name
	SandboxName string             `json:"-" url:"-"`
	Command     []string           `json:"command,omitempty" url:"-"`
	Env         map[string]*string `json:"env,omitempty" url:"-"`
	Name        string             `json:"name" url:"-"`
	TTL         *string            `json:"ttl,omitempty" url:"-"`
	User        *string            `json:"user,omitempty" url:"-"`
	Workdir     *string            `json:"workdir,omitempty" url:"-"`
}

type SandboxKillSessionRequest struct {
	// Sandbox name
	SandboxName string `json:"-" url:"-"`
	// Session name
	Session string `json:"-" url:"-"`
}

type SandboxListSessionsRequest struct {
	// Sandbox name
	SandboxName string `json:"-" url:"-"`
}

type CreateSessionResponse struct {
	Name   string `json:"name" url:"name"`
	Status string `json:"status" url:"status"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSessionResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSessionResponse) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateSessionResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateSessionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSessionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSessionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSessionResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ListSessionsResponse struct {
	Sessions []*SessionInfo `json:"sessions" url:"sessions"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSessionsResponse) GetSessions() []*SessionInfo {
	if l == nil {
		return nil
	}
	return l.Sessions
}

func (l *ListSessionsResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListSessionsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSessionsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSessionsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSessionsResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type SessionInfo struct {
	Name            string        `json:"name" url:"name"`
	StartedAtUnixMs *int64        `json:"started_at_unix_ms,omitempty" url:"started_at_unix_ms,omitempty"`
	Status          SessionStatus `json:"status" url:"status"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SessionInfo) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SessionInfo) GetStartedAtUnixMs() *int64 {
	if s == nil {
		return nil
	}
	return s.StartedAtUnixMs
}

func (s *SessionInfo) GetStatus() SessionStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *SessionInfo) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SessionInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler SessionInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SessionInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SessionInfo) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SessionStatus string

const (
	SessionStatusConnected    SessionStatus = "connected"
	SessionStatusDisconnected SessionStatus = "disconnected"
	SessionStatusDead         SessionStatus = "dead"
)

func NewSessionStatusFromString(s string) (SessionStatus, error) {
	switch s {
	case "connected":
		return SessionStatusConnected, nil
	case "disconnected":
		return SessionStatusDisconnected, nil
	case "dead":
		return SessionStatusDead, nil
	}
	var t SessionStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SessionStatus) Ptr() *SessionStatus {
	return &s
}
