// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
)

type CreateTenant struct {
	Name string `json:"name" url:"-"`
}

type CreateTenantResponse struct {
	PublicID  string `json:"public_id" url:"public_id"`
	Name      string `json:"name" url:"name"`
	DescopeID string `json:"descope_id" url:"descope_id"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateTenantResponse) GetPublicID() string {
	if c == nil {
		return ""
	}
	return c.PublicID
}

func (c *CreateTenantResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateTenantResponse) GetDescopeID() string {
	if c == nil {
		return ""
	}
	return c.DescopeID
}

func (c *CreateTenantResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateTenantResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTenantResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateTenantResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateTenantResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type PublicSubscription struct {
	Tier *string `json:"tier,omitempty" url:"tier,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PublicSubscription) GetTier() *string {
	if p == nil {
		return nil
	}
	return p.Tier
}

func (p *PublicSubscription) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PublicSubscription) UnmarshalJSON(data []byte) error {
	type unmarshaler PublicSubscription
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PublicSubscription(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PublicSubscription) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PublicTenant struct {
	PublicID  string `json:"public_id" url:"public_id"`
	Name      string `json:"name" url:"name"`
	IsEnabled bool   `json:"is_enabled" url:"is_enabled"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PublicTenant) GetPublicID() string {
	if p == nil {
		return ""
	}
	return p.PublicID
}

func (p *PublicTenant) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PublicTenant) GetIsEnabled() bool {
	if p == nil {
		return false
	}
	return p.IsEnabled
}

func (p *PublicTenant) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PublicTenant) UnmarshalJSON(data []byte) error {
	type unmarshaler PublicTenant
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PublicTenant(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PublicTenant) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type TenantSettingsResponse struct {
	Data map[string]interface{} `json:"data" url:"data"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TenantSettingsResponse) GetData() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TenantSettingsResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TenantSettingsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TenantSettingsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TenantSettingsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TenantSettingsResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TenantSettingsUpdate struct {
	Data map[string]interface{} `json:"data,omitempty" url:"-"`
}
