// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersComputeRegionResponse(t *testing.T) {
	t.Run("SetKey", func(t *testing.T) {
		obj := &ComputeRegionResponse{}
		var fernTestValueKey string
		obj.SetKey(fernTestValueKey)
		assert.Equal(t, fernTestValueKey, obj.Key)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLabel", func(t *testing.T) {
		obj := &ComputeRegionResponse{}
		var fernTestValueLabel string
		obj.SetLabel(fernTestValueLabel)
		assert.Equal(t, fernTestValueLabel, obj.Label)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetApiUrl", func(t *testing.T) {
		obj := &ComputeRegionResponse{}
		var fernTestValueApiUrl string
		obj.SetApiUrl(fernTestValueApiUrl)
		assert.Equal(t, fernTestValueApiUrl, obj.ApiUrl)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWsURL", func(t *testing.T) {
		obj := &ComputeRegionResponse{}
		var fernTestValueWsURL string
		obj.SetWsURL(fernTestValueWsURL)
		assert.Equal(t, fernTestValueWsURL, obj.WsURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsDefault", func(t *testing.T) {
		obj := &ComputeRegionResponse{}
		var fernTestValueIsDefault *bool
		obj.SetIsDefault(fernTestValueIsDefault)
		assert.Equal(t, fernTestValueIsDefault, obj.IsDefault)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersComputeRegionResponse(t *testing.T) {
	t.Run("GetKey", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var expected string
		obj.Key = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKey(), "getter should return the property value")
	})

	t.Run("GetKey_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ComputeRegionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKey() // Should return zero value
	})

	t.Run("GetLabel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var expected string
		obj.Label = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLabel(), "getter should return the property value")
	})

	t.Run("GetLabel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ComputeRegionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLabel() // Should return zero value
	})

	t.Run("GetApiUrl", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var expected string
		obj.ApiUrl = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetApiUrl(), "getter should return the property value")
	})

	t.Run("GetApiUrl_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ComputeRegionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetApiUrl() // Should return zero value
	})

	t.Run("GetWsURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var expected string
		obj.WsURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWsURL(), "getter should return the property value")
	})

	t.Run("GetWsURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ComputeRegionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWsURL() // Should return zero value
	})

	t.Run("GetIsDefault", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var expected *bool
		obj.IsDefault = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsDefault(), "getter should return the property value")
	})

	t.Run("GetIsDefault_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		obj.IsDefault = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsDefault(), "getter should return nil when property is nil")
	})

	t.Run("GetIsDefault_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ComputeRegionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsDefault() // Should return zero value
	})

}

func TestSettersMarkExplicitComputeRegionResponse(t *testing.T) {
	t.Run("SetKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var fernTestValueKey string

		// Act
		obj.SetKey(fernTestValueKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLabel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var fernTestValueLabel string

		// Act
		obj.SetLabel(fernTestValueLabel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetApiUrl_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var fernTestValueApiUrl string

		// Act
		obj.SetApiUrl(fernTestValueApiUrl)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWsURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var fernTestValueWsURL string

		// Act
		obj.SetWsURL(fernTestValueWsURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsDefault_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}
		var fernTestValueIsDefault *bool

		// Act
		obj.SetIsDefault(fernTestValueIsDefault)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTenantRegionsResponse(t *testing.T) {
	t.Run("SetRegions", func(t *testing.T) {
		obj := &TenantRegionsResponse{}
		var fernTestValueRegions []*ComputeRegionResponse
		obj.SetRegions(fernTestValueRegions)
		assert.Equal(t, fernTestValueRegions, obj.Regions)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTenantRegionsResponse(t *testing.T) {
	t.Run("GetRegions", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TenantRegionsResponse{}
		var expected []*ComputeRegionResponse
		obj.Regions = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRegions(), "getter should return the property value")
	})

	t.Run("GetRegions_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TenantRegionsResponse{}
		obj.Regions = nil

		// Act & Assert
		assert.Nil(t, obj.GetRegions(), "getter should return nil when property is nil")
	})

	t.Run("GetRegions_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TenantRegionsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRegions() // Should return zero value
	})

}

func TestSettersMarkExplicitTenantRegionsResponse(t *testing.T) {
	t.Run("SetRegions_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TenantRegionsResponse{}
		var fernTestValueRegions []*ComputeRegionResponse

		// Act
		obj.SetRegions(fernTestValueRegions)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingComputeRegionResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ComputeRegionResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ComputeRegionResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ComputeRegionResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ComputeRegionResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTenantRegionsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TenantRegionsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TenantRegionsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TenantRegionsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TenantRegionsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringComputeRegionResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ComputeRegionResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ComputeRegionResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTenantRegionsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TenantRegionsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TenantRegionsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesComputeRegionResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ComputeRegionResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ComputeRegionResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTenantRegionsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TenantRegionsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TenantRegionsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
