// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
)

// Structured error response for API clients.
type ErrorResponse struct {
	Code      IsloErrorCode          `json:"code" url:"code"`
	Message   string                 `json:"message" url:"message"`
	Hint      *string                `json:"hint,omitempty" url:"hint,omitempty"`
	Details   map[string]interface{} `json:"details,omitempty" url:"details,omitempty"`
	RequestID *string                `json:"request_id,omitempty" url:"request_id,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponse) GetCode() IsloErrorCode {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *ErrorResponse) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *ErrorResponse) GetHint() *string {
	if e == nil {
		return nil
	}
	return e.Hint
}

func (e *ErrorResponse) GetDetails() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.Details
}

func (e *ErrorResponse) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *ErrorResponse) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponse) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type HTTPValidationError struct {
	Detail []*ValidationError `json:"detail,omitempty" url:"detail,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (h *HTTPValidationError) GetDetail() []*ValidationError {
	if h == nil {
		return nil
	}
	return h.Detail
}

func (h *HTTPValidationError) GetExtraProperties() map[string]interface{} {
	return h.extraProperties
}

func (h *HTTPValidationError) UnmarshalJSON(data []byte) error {
	type unmarshaler HTTPValidationError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HTTPValidationError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties
	h.rawJSON = json.RawMessage(data)
	return nil
}

func (h *HTTPValidationError) String() string {
	if len(h.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(h.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

// Machine-readable error codes for API responses.
type IsloErrorCode string

const (
	IsloErrorCodeAuthRequired         IsloErrorCode = "AUTH_REQUIRED"
	IsloErrorCodeAuthTokenExpired     IsloErrorCode = "AUTH_TOKEN_EXPIRED"
	IsloErrorCodeAuthTokenInvalid     IsloErrorCode = "AUTH_TOKEN_INVALID"
	IsloErrorCodeAccessDenied         IsloErrorCode = "ACCESS_DENIED"
	IsloErrorCodeSandboxNotFound      IsloErrorCode = "SANDBOX_NOT_FOUND"
	IsloErrorCodeSandboxAlreadyExists IsloErrorCode = "SANDBOX_ALREADY_EXISTS"
	IsloErrorCodeSandboxNotRunning    IsloErrorCode = "SANDBOX_NOT_RUNNING"
	IsloErrorCodeSandboxInvalidState  IsloErrorCode = "SANDBOX_INVALID_STATE"
	IsloErrorCodeCommandNotFound      IsloErrorCode = "COMMAND_NOT_FOUND"
	IsloErrorCodeExecFailed           IsloErrorCode = "EXEC_FAILED"
	IsloErrorCodeResourceUnavailable  IsloErrorCode = "RESOURCE_UNAVAILABLE"
	IsloErrorCodeResourceNotFound     IsloErrorCode = "RESOURCE_NOT_FOUND"
	IsloErrorCodeFileNotFound         IsloErrorCode = "FILE_NOT_FOUND"
	IsloErrorCodeCacheConflict        IsloErrorCode = "CACHE_CONFLICT"
	IsloErrorCodeRateLimited          IsloErrorCode = "RATE_LIMITED"
	IsloErrorCodeInsufficientCredits  IsloErrorCode = "INSUFFICIENT_CREDITS"
	IsloErrorCodeValidationError      IsloErrorCode = "VALIDATION_ERROR"
	IsloErrorCodeInvalidRequest       IsloErrorCode = "INVALID_REQUEST"
	IsloErrorCodeUpstreamError        IsloErrorCode = "UPSTREAM_ERROR"
	IsloErrorCodeUpstreamTimeout      IsloErrorCode = "UPSTREAM_TIMEOUT"
	IsloErrorCodeUpstreamUnavailable  IsloErrorCode = "UPSTREAM_UNAVAILABLE"
	IsloErrorCodeTimeout              IsloErrorCode = "TIMEOUT"
	IsloErrorCodeInternalError        IsloErrorCode = "INTERNAL_ERROR"
)

func NewIsloErrorCodeFromString(s string) (IsloErrorCode, error) {
	switch s {
	case "AUTH_REQUIRED":
		return IsloErrorCodeAuthRequired, nil
	case "AUTH_TOKEN_EXPIRED":
		return IsloErrorCodeAuthTokenExpired, nil
	case "AUTH_TOKEN_INVALID":
		return IsloErrorCodeAuthTokenInvalid, nil
	case "ACCESS_DENIED":
		return IsloErrorCodeAccessDenied, nil
	case "SANDBOX_NOT_FOUND":
		return IsloErrorCodeSandboxNotFound, nil
	case "SANDBOX_ALREADY_EXISTS":
		return IsloErrorCodeSandboxAlreadyExists, nil
	case "SANDBOX_NOT_RUNNING":
		return IsloErrorCodeSandboxNotRunning, nil
	case "SANDBOX_INVALID_STATE":
		return IsloErrorCodeSandboxInvalidState, nil
	case "COMMAND_NOT_FOUND":
		return IsloErrorCodeCommandNotFound, nil
	case "EXEC_FAILED":
		return IsloErrorCodeExecFailed, nil
	case "RESOURCE_UNAVAILABLE":
		return IsloErrorCodeResourceUnavailable, nil
	case "RESOURCE_NOT_FOUND":
		return IsloErrorCodeResourceNotFound, nil
	case "FILE_NOT_FOUND":
		return IsloErrorCodeFileNotFound, nil
	case "CACHE_CONFLICT":
		return IsloErrorCodeCacheConflict, nil
	case "RATE_LIMITED":
		return IsloErrorCodeRateLimited, nil
	case "INSUFFICIENT_CREDITS":
		return IsloErrorCodeInsufficientCredits, nil
	case "VALIDATION_ERROR":
		return IsloErrorCodeValidationError, nil
	case "INVALID_REQUEST":
		return IsloErrorCodeInvalidRequest, nil
	case "UPSTREAM_ERROR":
		return IsloErrorCodeUpstreamError, nil
	case "UPSTREAM_TIMEOUT":
		return IsloErrorCodeUpstreamTimeout, nil
	case "UPSTREAM_UNAVAILABLE":
		return IsloErrorCodeUpstreamUnavailable, nil
	case "TIMEOUT":
		return IsloErrorCodeTimeout, nil
	case "INTERNAL_ERROR":
		return IsloErrorCodeInternalError, nil
	}
	var t IsloErrorCode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IsloErrorCode) Ptr() *IsloErrorCode {
	return &i
}

type TenantLimits struct {
	MaxConcurrentSandboxes int `json:"max_concurrent_sandboxes" url:"max_concurrent_sandboxes"`
	GlobalRpm              int `json:"global_rpm" url:"global_rpm"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TenantLimits) GetMaxConcurrentSandboxes() int {
	if t == nil {
		return 0
	}
	return t.MaxConcurrentSandboxes
}

func (t *TenantLimits) GetGlobalRpm() int {
	if t == nil {
		return 0
	}
	return t.GlobalRpm
}

func (t *TenantLimits) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TenantLimits) UnmarshalJSON(data []byte) error {
	type unmarshaler TenantLimits
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TenantLimits(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TenantLimits) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TenantStatus string

const (
	TenantStatusActive           TenantStatus = "active"
	TenantStatusSuspended        TenantStatus = "suspended"
	TenantStatusCreditsExhausted TenantStatus = "credits_exhausted"
)

func NewTenantStatusFromString(s string) (TenantStatus, error) {
	switch s {
	case "active":
		return TenantStatusActive, nil
	case "suspended":
		return TenantStatusSuspended, nil
	case "credits_exhausted":
		return TenantStatusCreditsExhausted, nil
	}
	var t TenantStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TenantStatus) Ptr() *TenantStatus {
	return &t
}

// Request to exchange a Descope access key for a session token.
type TokenRequest struct {
	// Descope access key to exchange for a session JWT
	AccessKey string `json:"access_key" url:"access_key"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TokenRequest) GetAccessKey() string {
	if t == nil {
		return ""
	}
	return t.AccessKey
}

func (t *TokenRequest) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenRequest) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Response containing the session JWT.
type TokenResponse struct {
	// Descope session JWT
	SessionToken string `json:"session_token" url:"session_token"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TokenResponse) GetSessionToken() string {
	if t == nil {
		return ""
	}
	return t.SessionToken
}

func (t *TokenResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type ValidationError struct {
	Loc   []*ValidationErrorLocItem `json:"loc" url:"loc"`
	Msg   string                    `json:"msg" url:"msg"`
	Type  string                    `json:"type" url:"type"`
	Input interface{}               `json:"input,omitempty" url:"input,omitempty"`
	Ctx   map[string]interface{}    `json:"ctx,omitempty" url:"ctx,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *ValidationError) GetLoc() []*ValidationErrorLocItem {
	if v == nil {
		return nil
	}
	return v.Loc
}

func (v *ValidationError) GetMsg() string {
	if v == nil {
		return ""
	}
	return v.Msg
}

func (v *ValidationError) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *ValidationError) GetInput() interface{} {
	if v == nil {
		return nil
	}
	return v.Input
}

func (v *ValidationError) GetCtx() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.Ctx
}

func (v *ValidationError) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *ValidationError) UnmarshalJSON(data []byte) error {
	type unmarshaler ValidationError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ValidationError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *ValidationError) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type ValidationErrorLocItem struct {
	String  string
	Integer int

	typ string
}

func (v *ValidationErrorLocItem) GetString() string {
	if v == nil {
		return ""
	}
	return v.String
}

func (v *ValidationErrorLocItem) GetInteger() int {
	if v == nil {
		return 0
	}
	return v.Integer
}

func (v *ValidationErrorLocItem) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		v.typ = "String"
		v.String = valueString
		return nil
	}
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		v.typ = "Integer"
		v.Integer = valueInteger
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, v)
}

func (v ValidationErrorLocItem) MarshalJSON() ([]byte, error) {
	if v.typ == "String" || v.String != "" {
		return json.Marshal(v.String)
	}
	if v.typ == "Integer" || v.Integer != 0 {
		return json.Marshal(v.Integer)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", v)
}

type ValidationErrorLocItemVisitor interface {
	VisitString(string) error
	VisitInteger(int) error
}

func (v *ValidationErrorLocItem) Accept(visitor ValidationErrorLocItemVisitor) error {
	if v.typ == "String" || v.String != "" {
		return visitor.VisitString(v.String)
	}
	if v.typ == "Integer" || v.Integer != 0 {
		return visitor.VisitInteger(v.Integer)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", v)
}
