// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
)

type ErrorCode string

const (
	ErrorCodeAuthRequired         ErrorCode = "AUTH_REQUIRED"
	ErrorCodeInvalidRequest       ErrorCode = "INVALID_REQUEST"
	ErrorCodeNotFound             ErrorCode = "NOT_FOUND"
	ErrorCodeValidationError      ErrorCode = "VALIDATION_ERROR"
	ErrorCodeSandboxNotFound      ErrorCode = "SANDBOX_NOT_FOUND"
	ErrorCodeSandboxAlreadyExists ErrorCode = "SANDBOX_ALREADY_EXISTS"
	ErrorCodeSandboxInvalidState  ErrorCode = "SANDBOX_INVALID_STATE"
	ErrorCodeResourceNotFound     ErrorCode = "RESOURCE_NOT_FOUND"
	ErrorCodeFileNotFound         ErrorCode = "FILE_NOT_FOUND"
	ErrorCodeCommandNotFound      ErrorCode = "COMMAND_NOT_FOUND"
	ErrorCodeExecFailed           ErrorCode = "EXEC_FAILED"
	ErrorCodeFileOperationError   ErrorCode = "FILE_OPERATION_ERROR"
	ErrorCodeResourceUnavailable  ErrorCode = "RESOURCE_UNAVAILABLE"
	ErrorCodeAccessDenied         ErrorCode = "ACCESS_DENIED"
	ErrorCodeCacheConflict        ErrorCode = "CACHE_CONFLICT"
	ErrorCodeBillingNotAllowed    ErrorCode = "BILLING_NOT_ALLOWED"
	ErrorCodeTenantSuspended      ErrorCode = "TENANT_SUSPENDED"
	ErrorCodeRateLimited          ErrorCode = "RATE_LIMITED"
	ErrorCodeTimeout              ErrorCode = "TIMEOUT"
	ErrorCodeInternalError        ErrorCode = "INTERNAL_ERROR"
)

func NewErrorCodeFromString(s string) (ErrorCode, error) {
	switch s {
	case "AUTH_REQUIRED":
		return ErrorCodeAuthRequired, nil
	case "INVALID_REQUEST":
		return ErrorCodeInvalidRequest, nil
	case "NOT_FOUND":
		return ErrorCodeNotFound, nil
	case "VALIDATION_ERROR":
		return ErrorCodeValidationError, nil
	case "SANDBOX_NOT_FOUND":
		return ErrorCodeSandboxNotFound, nil
	case "SANDBOX_ALREADY_EXISTS":
		return ErrorCodeSandboxAlreadyExists, nil
	case "SANDBOX_INVALID_STATE":
		return ErrorCodeSandboxInvalidState, nil
	case "RESOURCE_NOT_FOUND":
		return ErrorCodeResourceNotFound, nil
	case "FILE_NOT_FOUND":
		return ErrorCodeFileNotFound, nil
	case "COMMAND_NOT_FOUND":
		return ErrorCodeCommandNotFound, nil
	case "EXEC_FAILED":
		return ErrorCodeExecFailed, nil
	case "FILE_OPERATION_ERROR":
		return ErrorCodeFileOperationError, nil
	case "RESOURCE_UNAVAILABLE":
		return ErrorCodeResourceUnavailable, nil
	case "ACCESS_DENIED":
		return ErrorCodeAccessDenied, nil
	case "CACHE_CONFLICT":
		return ErrorCodeCacheConflict, nil
	case "BILLING_NOT_ALLOWED":
		return ErrorCodeBillingNotAllowed, nil
	case "TENANT_SUSPENDED":
		return ErrorCodeTenantSuspended, nil
	case "RATE_LIMITED":
		return ErrorCodeRateLimited, nil
	case "TIMEOUT":
		return ErrorCodeTimeout, nil
	case "INTERNAL_ERROR":
		return ErrorCodeInternalError, nil
	}
	var t ErrorCode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e ErrorCode) Ptr() *ErrorCode {
	return &e
}

type ErrorResponse struct {
	Available *int64    `json:"available,omitempty" url:"available,omitempty"`
	Code      ErrorCode `json:"code" url:"code"`
	Limit     *int64    `json:"limit,omitempty" url:"limit,omitempty"`
	Message   string    `json:"message" url:"message"`
	RequestID *string   `json:"request_id,omitempty" url:"request_id,omitempty"`
	Requested *int64    `json:"requested,omitempty" url:"requested,omitempty"`
	// Optional capacity fields populated for `InsufficientResources` errors so
	// clients (including peer agents) can recover the typed payload across
	// HTTP boundaries instead of collapsing it to an opaque message.
	Resource *string `json:"resource,omitempty" url:"resource,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponse) GetAvailable() *int64 {
	if e == nil {
		return nil
	}
	return e.Available
}

func (e *ErrorResponse) GetCode() ErrorCode {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *ErrorResponse) GetLimit() *int64 {
	if e == nil {
		return nil
	}
	return e.Limit
}

func (e *ErrorResponse) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *ErrorResponse) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *ErrorResponse) GetRequested() *int64 {
	if e == nil {
		return nil
	}
	return e.Requested
}

func (e *ErrorResponse) GetResource() *string {
	if e == nil {
		return nil
	}
	return e.Resource
}

func (e *ErrorResponse) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponse) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type HTTPValidationError struct {
	Detail []*ValidationError `json:"detail,omitempty" url:"detail,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (h *HTTPValidationError) GetDetail() []*ValidationError {
	if h == nil {
		return nil
	}
	return h.Detail
}

func (h *HTTPValidationError) GetExtraProperties() map[string]interface{} {
	return h.extraProperties
}

func (h *HTTPValidationError) UnmarshalJSON(data []byte) error {
	type unmarshaler HTTPValidationError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HTTPValidationError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties
	h.rawJSON = json.RawMessage(data)
	return nil
}

func (h *HTTPValidationError) String() string {
	if len(h.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(h.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

// Machine-readable error codes for API responses.
type IsloErrorCode string

const (
	IsloErrorCodeAuthRequired        IsloErrorCode = "AUTH_REQUIRED"
	IsloErrorCodeAuthTokenExpired    IsloErrorCode = "AUTH_TOKEN_EXPIRED"
	IsloErrorCodeAuthTokenInvalid    IsloErrorCode = "AUTH_TOKEN_INVALID"
	IsloErrorCodeAccessDenied        IsloErrorCode = "ACCESS_DENIED"
	IsloErrorCodeResourceUnavailable IsloErrorCode = "RESOURCE_UNAVAILABLE"
	IsloErrorCodeResourceNotFound    IsloErrorCode = "RESOURCE_NOT_FOUND"
	IsloErrorCodeRateLimited         IsloErrorCode = "RATE_LIMITED"
	IsloErrorCodeInsufficientCredits IsloErrorCode = "INSUFFICIENT_CREDITS"
	IsloErrorCodeValidationError     IsloErrorCode = "VALIDATION_ERROR"
	IsloErrorCodeInvalidRequest      IsloErrorCode = "INVALID_REQUEST"
	IsloErrorCodeUpstreamError       IsloErrorCode = "UPSTREAM_ERROR"
	IsloErrorCodeUpstreamTimeout     IsloErrorCode = "UPSTREAM_TIMEOUT"
	IsloErrorCodeUpstreamUnavailable IsloErrorCode = "UPSTREAM_UNAVAILABLE"
	IsloErrorCodeTimeout             IsloErrorCode = "TIMEOUT"
	IsloErrorCodeInternalError       IsloErrorCode = "INTERNAL_ERROR"
)

func NewIsloErrorCodeFromString(s string) (IsloErrorCode, error) {
	switch s {
	case "AUTH_REQUIRED":
		return IsloErrorCodeAuthRequired, nil
	case "AUTH_TOKEN_EXPIRED":
		return IsloErrorCodeAuthTokenExpired, nil
	case "AUTH_TOKEN_INVALID":
		return IsloErrorCodeAuthTokenInvalid, nil
	case "ACCESS_DENIED":
		return IsloErrorCodeAccessDenied, nil
	case "RESOURCE_UNAVAILABLE":
		return IsloErrorCodeResourceUnavailable, nil
	case "RESOURCE_NOT_FOUND":
		return IsloErrorCodeResourceNotFound, nil
	case "RATE_LIMITED":
		return IsloErrorCodeRateLimited, nil
	case "INSUFFICIENT_CREDITS":
		return IsloErrorCodeInsufficientCredits, nil
	case "VALIDATION_ERROR":
		return IsloErrorCodeValidationError, nil
	case "INVALID_REQUEST":
		return IsloErrorCodeInvalidRequest, nil
	case "UPSTREAM_ERROR":
		return IsloErrorCodeUpstreamError, nil
	case "UPSTREAM_TIMEOUT":
		return IsloErrorCodeUpstreamTimeout, nil
	case "UPSTREAM_UNAVAILABLE":
		return IsloErrorCodeUpstreamUnavailable, nil
	case "TIMEOUT":
		return IsloErrorCodeTimeout, nil
	case "INTERNAL_ERROR":
		return IsloErrorCodeInternalError, nil
	}
	var t IsloErrorCode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IsloErrorCode) Ptr() *IsloErrorCode {
	return &i
}

type ValidationError struct {
	Loc   []*ValidationErrorLocItem `json:"loc" url:"loc"`
	Msg   string                    `json:"msg" url:"msg"`
	Type  string                    `json:"type" url:"type"`
	Input interface{}               `json:"input,omitempty" url:"input,omitempty"`
	Ctx   map[string]interface{}    `json:"ctx,omitempty" url:"ctx,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *ValidationError) GetLoc() []*ValidationErrorLocItem {
	if v == nil {
		return nil
	}
	return v.Loc
}

func (v *ValidationError) GetMsg() string {
	if v == nil {
		return ""
	}
	return v.Msg
}

func (v *ValidationError) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *ValidationError) GetInput() interface{} {
	if v == nil {
		return nil
	}
	return v.Input
}

func (v *ValidationError) GetCtx() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.Ctx
}

func (v *ValidationError) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *ValidationError) UnmarshalJSON(data []byte) error {
	type unmarshaler ValidationError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ValidationError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *ValidationError) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type ValidationErrorLocItem struct {
	String  string
	Integer int

	typ string
}

func (v *ValidationErrorLocItem) GetString() string {
	if v == nil {
		return ""
	}
	return v.String
}

func (v *ValidationErrorLocItem) GetInteger() int {
	if v == nil {
		return 0
	}
	return v.Integer
}

func (v *ValidationErrorLocItem) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		v.typ = "String"
		v.String = valueString
		return nil
	}
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		v.typ = "Integer"
		v.Integer = valueInteger
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, v)
}

func (v ValidationErrorLocItem) MarshalJSON() ([]byte, error) {
	if v.typ == "String" || v.String != "" {
		return json.Marshal(v.String)
	}
	if v.typ == "Integer" || v.Integer != 0 {
		return json.Marshal(v.Integer)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", v)
}

type ValidationErrorLocItemVisitor interface {
	VisitString(string) error
	VisitInteger(int) error
}

func (v *ValidationErrorLocItem) Accept(visitor ValidationErrorLocItemVisitor) error {
	if v.typ == "String" || v.String != "" {
		return visitor.VisitString(v.String)
	}
	if v.typ == "Integer" || v.Integer != 0 {
		return visitor.VisitInteger(v.Integer)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", v)
}
