// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/islo-labs/go-sdk/internal"
)

type InviteUserRequest struct {
	Email string `json:"email" url:"-"`
}

type InviteUserResponse struct {
	Email   string `json:"email" url:"email"`
	Message string `json:"message" url:"message"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InviteUserResponse) GetEmail() string {
	if i == nil {
		return ""
	}
	return i.Email
}

func (i *InviteUserResponse) GetMessage() string {
	if i == nil {
		return ""
	}
	return i.Message
}

func (i *InviteUserResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InviteUserResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InviteUserResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InviteUserResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InviteUserResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}
