// Code generated by Fern. DO NOT EDIT.

package knowledge_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	strings "strings"
	testing "testing"

	gosdk "github.com/islo-labs/go-sdk"
	client "github.com/islo-labs/go-sdk/client"
	option "github.com/islo-labs/go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestKnowledgeListKnowledgeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.ListKnowledgeRequest{}
	_, invocationErr := client.Knowledge.ListKnowledge(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeListKnowledgeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeListKnowledgeWithWireMock", "GET", "/knowledge", nil, 1)
}

func TestKnowledgeCreateKnowledgeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.KnowledgeItemCreate{
		Slug: "slug",
	}
	_, invocationErr := client.Knowledge.CreateKnowledge(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeCreateKnowledgeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeCreateKnowledgeWithWireMock", "POST", "/knowledge", nil, 1)
}

func TestKnowledgeListKnowledgeTagsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	_, invocationErr := client.Knowledge.ListKnowledgeTags(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeListKnowledgeTagsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeListKnowledgeTagsWithWireMock", "GET", "/knowledge/tags", nil, 1)
}

func TestKnowledgeCreateKnowledgeMediaWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.BodyCreateKnowledgeMedia{
		File: strings.NewReader(
			"",
		),
		Item: "item",
	}
	_, invocationErr := client.Knowledge.CreateKnowledgeMedia(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeCreateKnowledgeMediaWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeCreateKnowledgeMediaWithWireMock", "POST", "/knowledge/upload", nil, 1)
}

func TestKnowledgeGetKnowledgeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.GetKnowledgeRequest{
		Identifier: "identifier",
	}
	_, invocationErr := client.Knowledge.GetKnowledge(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeGetKnowledgeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeGetKnowledgeWithWireMock", "GET", "/knowledge/identifier", nil, 1)
}

func TestKnowledgeDeleteKnowledgeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.DeleteKnowledgeRequest{
		Identifier: "identifier",
	}
	invocationErr := client.Knowledge.DeleteKnowledge(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeDeleteKnowledgeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeDeleteKnowledgeWithWireMock", "DELETE", "/knowledge/identifier", nil, 1)
}

func TestKnowledgeUpdateKnowledgeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.KnowledgeItemUpdate{
		Identifier: "identifier",
	}
	_, invocationErr := client.Knowledge.UpdateKnowledge(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeUpdateKnowledgeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeUpdateKnowledgeWithWireMock", "PATCH", "/knowledge/identifier", nil, 1)
}

func TestKnowledgeGetKnowledgeContentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.GetKnowledgeContentRequest{
		Identifier: "identifier",
	}
	_, invocationErr := client.Knowledge.GetKnowledgeContent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeGetKnowledgeContentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeGetKnowledgeContentWithWireMock", "GET", "/knowledge/identifier/content", nil, 1)
}

func TestKnowledgePutKnowledgeContentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.BodyPutKnowledgeContent{
		Identifier: "identifier",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.Knowledge.PutKnowledgeContent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgePutKnowledgeContentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgePutKnowledgeContentWithWireMock", "PUT", "/knowledge/identifier/content", nil, 1)
}

func TestKnowledgeListKnowledgeVersionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.ListKnowledgeVersionsRequest{
		Identifier: "identifier",
	}
	_, invocationErr := client.Knowledge.ListKnowledgeVersions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeListKnowledgeVersionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeListKnowledgeVersionsWithWireMock", "GET", "/knowledge/identifier/versions", nil, 1)
}

func TestKnowledgeGetKnowledgeVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.GetKnowledgeVersionRequest{
		Identifier:    "identifier",
		VersionNumber: 1,
	}
	_, invocationErr := client.Knowledge.GetKnowledgeVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeGetKnowledgeVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeGetKnowledgeVersionWithWireMock", "GET", "/knowledge/identifier/versions/1", nil, 1)
}

func TestKnowledgeGetKnowledgeVersionContentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.GetKnowledgeVersionContentRequest{
		Identifier:    "identifier",
		VersionNumber: 1,
	}
	_, invocationErr := client.Knowledge.GetKnowledgeVersionContent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeGetKnowledgeVersionContentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeGetKnowledgeVersionContentWithWireMock", "GET", "/knowledge/identifier/versions/1/content", nil, 1)
}

func TestKnowledgeRestoreKnowledgeVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewIslo(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-token"),
	)
	request := &gosdk.KnowledgeRestoreRequest{
		Identifier:    "identifier",
		VersionNumber: 1,
	}
	_, invocationErr := client.Knowledge.RestoreKnowledgeVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestKnowledgeRestoreKnowledgeVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestKnowledgeRestoreKnowledgeVersionWithWireMock", "POST", "/knowledge/identifier/restore", nil, 1)
}
