// Code generated by Fern. DO NOT EDIT.

package sandboxes

import (
	bytes "bytes"
	context "context"
	io "io"
	http "net/http"

	gosdk "github.com/islo-labs/go-sdk"
	core "github.com/islo-labs/go-sdk/core"
	internal "github.com/islo-labs/go-sdk/internal"
	option "github.com/islo-labs/go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListSandboxes(
	ctx context.Context,
	request *gosdk.ListSandboxesRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.PaginatedSandboxResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := baseURL + "/sandboxes"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *gosdk.PaginatedSandboxResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.PaginatedSandboxResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateSandbox(
	ctx context.Context,
	request *gosdk.CreateSandboxRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.SandboxResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := baseURL + "/sandboxes"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *gosdk.SandboxResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.SandboxResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetSandboxByID(
	ctx context.Context,
	request *gosdk.GetSandboxByIDRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.SandboxResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/-/by-id/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *gosdk.SandboxResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.SandboxResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetSandbox(
	ctx context.Context,
	request *gosdk.GetSandboxRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.SandboxResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *gosdk.SandboxResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.SandboxResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteSandbox(
	ctx context.Context,
	request *gosdk.DeleteSandboxRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) SandboxCreationEvents(
	ctx context.Context,
	request *gosdk.SandboxCreationEventsRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/events",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) ExecInSandbox(
	ctx context.Context,
	request *gosdk.ExecInSandboxRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.ExecResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/exec",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *gosdk.ExecResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.ExecResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ExecInSandboxStream(
	ctx context.Context,
	request *gosdk.ExecInSandboxStreamRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/exec/stream",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) GetExecResult(
	ctx context.Context,
	request *gosdk.GetExecResultRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.ExecResultResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/exec/%v",
		request.SandboxName,
		request.ExecID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *gosdk.ExecResultResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.ExecResultResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DownloadFile(
	ctx context.Context,
	request *gosdk.DownloadFileRequest,
	opts ...option.RequestOption,
) (*core.Response[io.Reader], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/files",
		request.SandboxName,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	response := bytes.NewBuffer(nil)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[io.Reader]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UploadFile(
	ctx context.Context,
	request *gosdk.UploadFileRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.FileUploadStatusResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/files",
		request.SandboxName,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	writer := internal.NewMultipartWriter()
	if err := writer.WriteFile("file", request.File); err != nil {
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	headers.Set("Content-Type", writer.ContentType())

	var response *gosdk.FileUploadStatusResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         writer.Buffer(),
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.FileUploadStatusResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DownloadArchive(
	ctx context.Context,
	request *gosdk.DownloadArchiveRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/files-archive",
		request.SandboxName,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UploadArchive(
	ctx context.Context,
	request *gosdk.UploadArchiveRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.FileUploadStatusResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/files-archive",
		request.SandboxName,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	writer := internal.NewMultipartWriter()
	if err := writer.WriteFile("file", request.File); err != nil {
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	headers.Set("Content-Type", writer.ContentType())

	var response *gosdk.FileUploadStatusResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         writer.Buffer(),
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.FileUploadStatusResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PauseSandbox(
	ctx context.Context,
	request *gosdk.PauseSandboxRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.SandboxResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/pause",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *gosdk.SandboxResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.SandboxResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ResumeSandbox(
	ctx context.Context,
	request *gosdk.ResumeSandboxRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.SandboxResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/resume",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *gosdk.SandboxResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.SandboxResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListSessions(
	ctx context.Context,
	request *gosdk.ListSessionsRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.ListSessionsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/sessions",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *gosdk.ListSessionsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.ListSessionsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateSession(
	ctx context.Context,
	request *gosdk.CreateSessionRequest,
	opts ...option.RequestOption,
) (*core.Response[*gosdk.CreateSessionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/sessions",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *gosdk.CreateSessionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*gosdk.CreateSessionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) KillSession(
	ctx context.Context,
	request *gosdk.KillSessionRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/sessions/%v",
		request.SandboxName,
		request.Session,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) StopSandbox(
	ctx context.Context,
	request *gosdk.StopSandboxRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Compute",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Compute",
		),
		"https://ca.compute.islo.dev",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/sandboxes/%v/stop",
		request.SandboxName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(gosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}
